# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Mon Dec  3 00:44:10 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(507, 740)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(500, 620))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(500, 600))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab_1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cPath = QtGui.QLineEdit(self.groupBox)
        self.cPath.setText(_fromUtf8(""))
        self.cPath.setObjectName(_fromUtf8("cPath"))
        self.horizontalLayout.addWidget(self.cPath)
        self.cFile = QtGui.QPushButton(self.groupBox)
        self.cFile.setObjectName(_fromUtf8("cFile"))
        self.horizontalLayout.addWidget(self.cFile)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cYColumn = QtGui.QSpinBox(self.groupBox)
        self.cYColumn.setMinimum(0)
        self.cYColumn.setMaximum(100)
        self.cYColumn.setProperty("value", 4)
        self.cYColumn.setObjectName(_fromUtf8("cYColumn"))
        self.gridLayout_2.addWidget(self.cYColumn, 1, 1, 1, 1)
        self.cMColumn = QtGui.QSpinBox(self.groupBox)
        self.cMColumn.setMinimum(0)
        self.cMColumn.setMaximum(100)
        self.cMColumn.setProperty("value", 1)
        self.cMColumn.setObjectName(_fromUtf8("cMColumn"))
        self.gridLayout_2.addWidget(self.cMColumn, 1, 3, 1, 1)
        self.cXColumn = QtGui.QSpinBox(self.groupBox)
        self.cXColumn.setMinimum(0)
        self.cXColumn.setMaximum(100)
        self.cXColumn.setProperty("value", 5)
        self.cXColumn.setObjectName(_fromUtf8("cXColumn"))
        self.gridLayout_2.addWidget(self.cXColumn, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.cMCheck = QtGui.QCheckBox(self.groupBox)
        self.cMCheck.setEnabled(True)
        self.cMCheck.setCheckable(True)
        self.cMCheck.setChecked(True)
        self.cMCheck.setTristate(False)
        self.cMCheck.setObjectName(_fromUtf8("cMCheck"))
        self.gridLayout_2.addWidget(self.cMCheck, 0, 3, 1, 1)
        self.cXFilt = QtGui.QLineEdit(self.groupBox)
        self.cXFilt.setEnabled(False)
        self.cXFilt.setObjectName(_fromUtf8("cXFilt"))
        self.gridLayout_2.addWidget(self.cXFilt, 2, 0, 1, 1)
        self.cYFilt = QtGui.QLineEdit(self.groupBox)
        self.cYFilt.setEnabled(False)
        self.cYFilt.setObjectName(_fromUtf8("cYFilt"))
        self.gridLayout_2.addWidget(self.cYFilt, 2, 1, 1, 1)
        self.cFilt = QtGui.QCheckBox(self.groupBox)
        self.cFilt.setObjectName(_fromUtf8("cFilt"))
        self.gridLayout_2.addWidget(self.cFilt, 2, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.cLoad = QtGui.QPushButton(self.groupBox)
        self.cLoad.setEnabled(False)
        self.cLoad.setObjectName(_fromUtf8("cLoad"))
        self.verticalLayout_7.addWidget(self.cLoad)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_2.addWidget(self.label_33)
        self.sPath = QtGui.QLineEdit(self.groupBox_2)
        self.sPath.setText(_fromUtf8(""))
        self.sPath.setObjectName(_fromUtf8("sPath"))
        self.horizontalLayout_2.addWidget(self.sPath)
        self.sFile = QtGui.QPushButton(self.groupBox_2)
        self.sFile.setObjectName(_fromUtf8("sFile"))
        self.horizontalLayout_2.addWidget(self.sFile)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.sFilt = QtGui.QCheckBox(self.groupBox_2)
        self.sFilt.setObjectName(_fromUtf8("sFilt"))
        self.gridLayout_4.addWidget(self.sFilt, 2, 3, 1, 1)
        self.sXFilt = QtGui.QLineEdit(self.groupBox_2)
        self.sXFilt.setEnabled(False)
        self.sXFilt.setObjectName(_fromUtf8("sXFilt"))
        self.gridLayout_4.addWidget(self.sXFilt, 2, 0, 1, 1)
        self.sYFilt = QtGui.QLineEdit(self.groupBox_2)
        self.sYFilt.setEnabled(False)
        self.sYFilt.setObjectName(_fromUtf8("sYFilt"))
        self.gridLayout_4.addWidget(self.sYFilt, 2, 1, 1, 1)
        self.sMColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sMColumn.setMinimum(0)
        self.sMColumn.setMaximum(100)
        self.sMColumn.setProperty("value", 1)
        self.sMColumn.setObjectName(_fromUtf8("sMColumn"))
        self.gridLayout_4.addWidget(self.sMColumn, 1, 3, 1, 1)
        self.sYColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sYColumn.setMinimum(0)
        self.sYColumn.setMaximum(100)
        self.sYColumn.setProperty("value", 4)
        self.sYColumn.setObjectName(_fromUtf8("sYColumn"))
        self.gridLayout_4.addWidget(self.sYColumn, 1, 1, 1, 1)
        self.sXColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sXColumn.setMinimum(0)
        self.sXColumn.setMaximum(100)
        self.sXColumn.setProperty("value", 5)
        self.sXColumn.setObjectName(_fromUtf8("sXColumn"))
        self.gridLayout_4.addWidget(self.sXColumn, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.sMCheck = QtGui.QCheckBox(self.groupBox_2)
        self.sMCheck.setEnabled(True)
        self.sMCheck.setCheckable(True)
        self.sMCheck.setChecked(True)
        self.sMCheck.setTristate(False)
        self.sMCheck.setObjectName(_fromUtf8("sMCheck"))
        self.gridLayout_4.addWidget(self.sMCheck, 0, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.sLoad = QtGui.QPushButton(self.groupBox_2)
        self.sLoad.setEnabled(False)
        self.sLoad.setObjectName(_fromUtf8("sLoad"))
        self.verticalLayout_8.addWidget(self.sLoad)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 175))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_32 = QtGui.QLabel(self.groupBox_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_4.addWidget(self.label_32)
        self.LENGTH = QtGui.QLineEdit(self.groupBox_3)
        self.LENGTH.setObjectName(_fromUtf8("LENGTH"))
        self.horizontalLayout_4.addWidget(self.LENGTH)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cReset = QtGui.QPushButton(self.tab_2)
        self.cReset.setEnabled(False)
        self.cReset.setObjectName(_fromUtf8("cReset"))
        self.horizontalLayout_7.addWidget(self.cReset)
        self.cUndo = QtGui.QPushButton(self.tab_2)
        self.cUndo.setEnabled(False)
        self.cUndo.setObjectName(_fromUtf8("cUndo"))
        self.horizontalLayout_7.addWidget(self.cUndo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.cY_XScale = QtGui.QCheckBox(self.groupBox_4)
        self.cY_XScale.setObjectName(_fromUtf8("cY_XScale"))
        self.horizontalLayout_15.addWidget(self.cY_XScale)
        self.cLogScale = QtGui.QGroupBox(self.groupBox_4)
        self.cLogScale.setObjectName(_fromUtf8("cLogScale"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.cLogScale)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cXLogScale = QtGui.QCheckBox(self.cLogScale)
        self.cXLogScale.setEnabled(True)
        self.cXLogScale.setObjectName(_fromUtf8("cXLogScale"))
        self.horizontalLayout_3.addWidget(self.cXLogScale)
        self.cYLogScale = QtGui.QCheckBox(self.cLogScale)
        self.cYLogScale.setEnabled(True)
        self.cYLogScale.setObjectName(_fromUtf8("cYLogScale"))
        self.horizontalLayout_3.addWidget(self.cYLogScale)
        self.horizontalLayout_15.addWidget(self.cLogScale)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.cAllSliceConcat = QtGui.QComboBox(self.groupBox_6)
        self.cAllSliceConcat.setObjectName(_fromUtf8("cAllSliceConcat"))
        self.cAllSliceConcat.addItem(_fromUtf8(""))
        self.cAllSliceConcat.addItem(_fromUtf8(""))
        self.cAllSliceConcat.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.cAllSliceConcat)
        self.cStart = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.cStart.setMinimum(0.01)
        self.cStart.setMaximum(99999999.0)
        self.cStart.setSingleStep(0.5)
        self.cStart.setProperty("value", 0.01)
        self.cStart.setObjectName(_fromUtf8("cStart"))
        self.horizontalLayout_17.addWidget(self.cStart)
        self.cEnd = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.cEnd.setMinimum(0.01)
        self.cEnd.setMaximum(9999999.0)
        self.cEnd.setSingleStep(0.5)
        self.cEnd.setProperty("value", 0.01)
        self.cEnd.setObjectName(_fromUtf8("cEnd"))
        self.horizontalLayout_17.addWidget(self.cEnd)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 2, 1, 1)
        self.cPolyOk = QtGui.QPushButton(self.groupBox_5)
        self.cPolyOk.setObjectName(_fromUtf8("cPolyOk"))
        self.gridLayout_6.addWidget(self.cPolyOk, 2, 2, 1, 1)
        self.cPolyP = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyP.setDecimals(3)
        self.cPolyP.setMinimum(0.001)
        self.cPolyP.setMaximum(999.0)
        self.cPolyP.setSingleStep(0.01)
        self.cPolyP.setProperty("value", 0.9)
        self.cPolyP.setObjectName(_fromUtf8("cPolyP"))
        self.gridLayout_6.addWidget(self.cPolyP, 1, 1, 1, 1)
        self.cPolyM = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyM.setDecimals(0)
        self.cPolyM.setProperty("value", 6.0)
        self.cPolyM.setObjectName(_fromUtf8("cPolyM"))
        self.gridLayout_6.addWidget(self.cPolyM, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 1, 1, 1)
        self.cPolyN = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyN.setDecimals(0)
        self.cPolyN.setMinimum(0.0)
        self.cPolyN.setMaximum(9999.0)
        self.cPolyN.setProperty("value", 80.0)
        self.cPolyN.setObjectName(_fromUtf8("cPolyN"))
        self.gridLayout_6.addWidget(self.cPolyN, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.cAverageStep = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.cAverageStep.setDecimals(0)
        self.cAverageStep.setMinimum(1.0)
        self.cAverageStep.setMaximum(999999999.0)
        self.cAverageStep.setSingleStep(1.0)
        self.cAverageStep.setProperty("value", 2.0)
        self.cAverageStep.setObjectName(_fromUtf8("cAverageStep"))
        self.gridLayout.addWidget(self.cAverageStep, 1, 0, 1, 1)
        self.cAverageOk = QtGui.QPushButton(self.groupBox_7)
        self.cAverageOk.setObjectName(_fromUtf8("cAverageOk"))
        self.gridLayout.addWidget(self.cAverageOk, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.cB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineStep.setDecimals(3)
        self.cB_splineStep.setMinimum(0.001)
        self.cB_splineStep.setMaximum(999999999.0)
        self.cB_splineStep.setSingleStep(0.5)
        self.cB_splineStep.setProperty("value", 1.0)
        self.cB_splineStep.setObjectName(_fromUtf8("cB_splineStep"))
        self.gridLayout_7.addWidget(self.cB_splineStep, 1, 0, 1, 1)
        self.cB_splineS = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineS.setDecimals(4)
        self.cB_splineS.setMinimum(0.0)
        self.cB_splineS.setMaximum(999999999.0)
        self.cB_splineS.setSingleStep(0.05)
        self.cB_splineS.setProperty("value", 1500000.0)
        self.cB_splineS.setObjectName(_fromUtf8("cB_splineS"))
        self.gridLayout_7.addWidget(self.cB_splineS, 1, 1, 1, 1)
        self.cB_splineK = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineK.setDecimals(0)
        self.cB_splineK.setMaximum(5.0)
        self.cB_splineK.setProperty("value", 4.0)
        self.cB_splineK.setObjectName(_fromUtf8("cB_splineK"))
        self.gridLayout_7.addWidget(self.cB_splineK, 1, 2, 1, 1)
        self.cAutoB_splineS = QtGui.QCheckBox(self.groupBox_8)
        self.cAutoB_splineS.setObjectName(_fromUtf8("cAutoB_splineS"))
        self.gridLayout_7.addWidget(self.cAutoB_splineS, 2, 1, 1, 1)
        self.cB_splineOk = QtGui.QPushButton(self.groupBox_8)
        self.cB_splineOk.setObjectName(_fromUtf8("cB_splineOk"))
        self.gridLayout_7.addWidget(self.cB_splineOk, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.cMedFiltS = QtGui.QSpinBox(self.groupBox_9)
        self.cMedFiltS.setMinimum(1)
        self.cMedFiltS.setSingleStep(2)
        self.cMedFiltS.setProperty("value", 3)
        self.cMedFiltS.setObjectName(_fromUtf8("cMedFiltS"))
        self.horizontalLayout_12.addWidget(self.cMedFiltS)
        self.cMedFilt = QtGui.QPushButton(self.groupBox_9)
        self.cMedFilt.setObjectName(_fromUtf8("cMedFilt"))
        self.horizontalLayout_12.addWidget(self.cMedFilt)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.cSave = QtGui.QPushButton(self.tab_2)
        self.cSave.setObjectName(_fromUtf8("cSave"))
        self.verticalLayout_2.addWidget(self.cSave)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.sReset = QtGui.QPushButton(self.tab_3)
        self.sReset.setEnabled(False)
        self.sReset.setObjectName(_fromUtf8("sReset"))
        self.horizontalLayout_8.addWidget(self.sReset)
        self.sUndo = QtGui.QPushButton(self.tab_3)
        self.sUndo.setEnabled(False)
        self.sUndo.setObjectName(_fromUtf8("sUndo"))
        self.horizontalLayout_8.addWidget(self.sUndo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_14.setEnabled(True)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sY_XScale = QtGui.QCheckBox(self.groupBox_14)
        self.sY_XScale.setObjectName(_fromUtf8("sY_XScale"))
        self.horizontalLayout_5.addWidget(self.sY_XScale)
        self.sLogScale = QtGui.QGroupBox(self.groupBox_14)
        self.sLogScale.setObjectName(_fromUtf8("sLogScale"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.sLogScale)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.sYLogScale = QtGui.QCheckBox(self.sLogScale)
        self.sYLogScale.setEnabled(True)
        self.sYLogScale.setObjectName(_fromUtf8("sYLogScale"))
        self.horizontalLayout_6.addWidget(self.sYLogScale)
        self.sXLogScale = QtGui.QCheckBox(self.sLogScale)
        self.sXLogScale.setEnabled(True)
        self.sXLogScale.setObjectName(_fromUtf8("sXLogScale"))
        self.horizontalLayout_6.addWidget(self.sXLogScale)
        self.horizontalLayout_5.addWidget(self.sLogScale)
        self.verticalLayout_3.addWidget(self.groupBox_14)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sAllSliceConcat = QtGui.QComboBox(self.groupBox_13)
        self.sAllSliceConcat.setObjectName(_fromUtf8("sAllSliceConcat"))
        self.sAllSliceConcat.addItem(_fromUtf8(""))
        self.sAllSliceConcat.addItem(_fromUtf8(""))
        self.sAllSliceConcat.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.sAllSliceConcat)
        self.sStart = QtGui.QDoubleSpinBox(self.groupBox_13)
        self.sStart.setMinimum(0.01)
        self.sStart.setMaximum(99999999.0)
        self.sStart.setSingleStep(0.5)
        self.sStart.setProperty("value", 0.01)
        self.sStart.setObjectName(_fromUtf8("sStart"))
        self.horizontalLayout_9.addWidget(self.sStart)
        self.sEnd = QtGui.QDoubleSpinBox(self.groupBox_13)
        self.sEnd.setMinimum(0.01)
        self.sEnd.setMaximum(9999999.0)
        self.sEnd.setSingleStep(0.5)
        self.sEnd.setProperty("value", 0.01)
        self.sEnd.setObjectName(_fromUtf8("sEnd"))
        self.horizontalLayout_9.addWidget(self.sEnd)
        self.verticalLayout_3.addWidget(self.groupBox_13)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_11)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 0, 2, 1, 1)
        self.sPolyN = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyN.setDecimals(0)
        self.sPolyN.setMinimum(0.0)
        self.sPolyN.setMaximum(9999.0)
        self.sPolyN.setProperty("value", 80.0)
        self.sPolyN.setObjectName(_fromUtf8("sPolyN"))
        self.gridLayout_10.addWidget(self.sPolyN, 1, 0, 1, 1)
        self.sPolyP = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyP.setDecimals(3)
        self.sPolyP.setMinimum(0.001)
        self.sPolyP.setMaximum(999.0)
        self.sPolyP.setSingleStep(0.01)
        self.sPolyP.setProperty("value", 0.9)
        self.sPolyP.setObjectName(_fromUtf8("sPolyP"))
        self.gridLayout_10.addWidget(self.sPolyP, 1, 1, 1, 1)
        self.sPolyM = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyM.setDecimals(0)
        self.sPolyM.setProperty("value", 6.0)
        self.sPolyM.setObjectName(_fromUtf8("sPolyM"))
        self.gridLayout_10.addWidget(self.sPolyM, 1, 2, 1, 1)
        self.sPolyOk = QtGui.QPushButton(self.groupBox_11)
        self.sPolyOk.setObjectName(_fromUtf8("sPolyOk"))
        self.gridLayout_10.addWidget(self.sPolyOk, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.sAverageStep = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.sAverageStep.setDecimals(0)
        self.sAverageStep.setMinimum(1.0)
        self.sAverageStep.setMaximum(999999999.0)
        self.sAverageStep.setSingleStep(1.0)
        self.sAverageStep.setProperty("value", 2.0)
        self.sAverageStep.setObjectName(_fromUtf8("sAverageStep"))
        self.horizontalLayout_19.addWidget(self.sAverageStep)
        self.label_26 = QtGui.QLabel(self.groupBox_15)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_19.addWidget(self.label_26)
        self.sAverageOk = QtGui.QPushButton(self.groupBox_15)
        self.sAverageOk.setObjectName(_fromUtf8("sAverageOk"))
        self.horizontalLayout_19.addWidget(self.sAverageOk)
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_21 = QtGui.QLabel(self.groupBox_10)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_10)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_10)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.sB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineStep.setDecimals(3)
        self.sB_splineStep.setMinimum(0.001)
        self.sB_splineStep.setMaximum(999999999.0)
        self.sB_splineStep.setSingleStep(0.5)
        self.sB_splineStep.setProperty("value", 1.0)
        self.sB_splineStep.setObjectName(_fromUtf8("sB_splineStep"))
        self.gridLayout_3.addWidget(self.sB_splineStep, 1, 0, 1, 1)
        self.sB_splineS = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineS.setDecimals(4)
        self.sB_splineS.setMinimum(0.0)
        self.sB_splineS.setMaximum(999999999.0)
        self.sB_splineS.setSingleStep(0.05)
        self.sB_splineS.setProperty("value", 1500000.0)
        self.sB_splineS.setObjectName(_fromUtf8("sB_splineS"))
        self.gridLayout_3.addWidget(self.sB_splineS, 1, 1, 1, 1)
        self.sB_splineK = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineK.setDecimals(0)
        self.sB_splineK.setMaximum(5.0)
        self.sB_splineK.setProperty("value", 4.0)
        self.sB_splineK.setObjectName(_fromUtf8("sB_splineK"))
        self.gridLayout_3.addWidget(self.sB_splineK, 1, 2, 1, 1)
        self.sAutoB_splineS = QtGui.QCheckBox(self.groupBox_10)
        self.sAutoB_splineS.setObjectName(_fromUtf8("sAutoB_splineS"))
        self.gridLayout_3.addWidget(self.sAutoB_splineS, 2, 1, 1, 1)
        self.sB_splineOk = QtGui.QPushButton(self.groupBox_10)
        self.sB_splineOk.setObjectName(_fromUtf8("sB_splineOk"))
        self.gridLayout_3.addWidget(self.sB_splineOk, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 0, 1, 1)
        self.sMedFiltS = QtGui.QSpinBox(self.groupBox_12)
        self.sMedFiltS.setMinimum(1)
        self.sMedFiltS.setSingleStep(2)
        self.sMedFiltS.setProperty("value", 3)
        self.sMedFiltS.setObjectName(_fromUtf8("sMedFiltS"))
        self.gridLayout_9.addWidget(self.sMedFiltS, 0, 1, 1, 1)
        self.sMedFilt = QtGui.QPushButton(self.groupBox_12)
        self.sMedFilt.setObjectName(_fromUtf8("sMedFilt"))
        self.gridLayout_9.addWidget(self.sMedFilt, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.sSave = QtGui.QPushButton(self.tab_3)
        self.sSave.setObjectName(_fromUtf8("sSave"))
        self.verticalLayout_3.addWidget(self.sSave)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.rButton = QtGui.QPushButton(self.tab_4)
        self.rButton.setObjectName(_fromUtf8("rButton"))
        self.horizontalLayout_11.addWidget(self.rButton)
        self.rEvalType = QtGui.QComboBox(self.tab_4)
        self.rEvalType.setObjectName(_fromUtf8("rEvalType"))
        self.rEvalType.addItem(_fromUtf8(""))
        self.rEvalType.addItem(_fromUtf8(""))
        self.rEvalType.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.rEvalType)
        self.rReset = QtGui.QPushButton(self.tab_4)
        self.rReset.setEnabled(False)
        self.rReset.setObjectName(_fromUtf8("rReset"))
        self.horizontalLayout_11.addWidget(self.rReset)
        self.rUndo = QtGui.QPushButton(self.tab_4)
        self.rUndo.setEnabled(False)
        self.rUndo.setObjectName(_fromUtf8("rUndo"))
        self.horizontalLayout_11.addWidget(self.rUndo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_17 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.rY_XScale = QtGui.QCheckBox(self.groupBox_17)
        self.rY_XScale.setObjectName(_fromUtf8("rY_XScale"))
        self.horizontalLayout_16.addWidget(self.rY_XScale)
        self.rLogScale = QtGui.QGroupBox(self.groupBox_17)
        self.rLogScale.setObjectName(_fromUtf8("rLogScale"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.rLogScale)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.rXLogScale = QtGui.QCheckBox(self.rLogScale)
        self.rXLogScale.setObjectName(_fromUtf8("rXLogScale"))
        self.horizontalLayout_13.addWidget(self.rXLogScale)
        self.rYLogScale = QtGui.QCheckBox(self.rLogScale)
        self.rYLogScale.setObjectName(_fromUtf8("rYLogScale"))
        self.horizontalLayout_13.addWidget(self.rYLogScale)
        self.horizontalLayout_16.addWidget(self.rLogScale)
        self.verticalLayout_5.addWidget(self.groupBox_17)
        self.groupBox_18 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.rAllSliceConcat = QtGui.QComboBox(self.groupBox_18)
        self.rAllSliceConcat.setObjectName(_fromUtf8("rAllSliceConcat"))
        self.rAllSliceConcat.addItem(_fromUtf8(""))
        self.rAllSliceConcat.addItem(_fromUtf8(""))
        self.rAllSliceConcat.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.rAllSliceConcat)
        self.rStart = QtGui.QDoubleSpinBox(self.groupBox_18)
        self.rStart.setMinimum(0.01)
        self.rStart.setMaximum(99999999.0)
        self.rStart.setSingleStep(0.5)
        self.rStart.setProperty("value", 0.01)
        self.rStart.setObjectName(_fromUtf8("rStart"))
        self.horizontalLayout_18.addWidget(self.rStart)
        self.rEnd = QtGui.QDoubleSpinBox(self.groupBox_18)
        self.rEnd.setMinimum(0.01)
        self.rEnd.setMaximum(9999999.0)
        self.rEnd.setSingleStep(0.5)
        self.rEnd.setProperty("value", 0.01)
        self.rEnd.setObjectName(_fromUtf8("rEnd"))
        self.horizontalLayout_18.addWidget(self.rEnd)
        self.verticalLayout_5.addWidget(self.groupBox_18)
        self.groupBox_19 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_50 = QtGui.QLabel(self.groupBox_19)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_19)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_19)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 2, 1, 1)
        self.rB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineStep.setDecimals(4)
        self.rB_splineStep.setMinimum(0.001)
        self.rB_splineStep.setMaximum(99999.0)
        self.rB_splineStep.setSingleStep(0.5)
        self.rB_splineStep.setProperty("value", 1.0)
        self.rB_splineStep.setObjectName(_fromUtf8("rB_splineStep"))
        self.gridLayout_8.addWidget(self.rB_splineStep, 1, 0, 1, 1)
        self.rB_splineS = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineS.setDecimals(4)
        self.rB_splineS.setMinimum(0.0)
        self.rB_splineS.setMaximum(999999999.0)
        self.rB_splineS.setSingleStep(0.01)
        self.rB_splineS.setProperty("value", 10.0)
        self.rB_splineS.setObjectName(_fromUtf8("rB_splineS"))
        self.gridLayout_8.addWidget(self.rB_splineS, 1, 1, 1, 1)
        self.rB_splineK = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineK.setDecimals(0)
        self.rB_splineK.setMaximum(5.0)
        self.rB_splineK.setProperty("value", 4.0)
        self.rB_splineK.setObjectName(_fromUtf8("rB_splineK"))
        self.gridLayout_8.addWidget(self.rB_splineK, 1, 2, 1, 1)
        self.rAutoB_splineS = QtGui.QCheckBox(self.groupBox_19)
        self.rAutoB_splineS.setObjectName(_fromUtf8("rAutoB_splineS"))
        self.gridLayout_8.addWidget(self.rAutoB_splineS, 2, 1, 1, 1)
        self.rB_splineOk = QtGui.QPushButton(self.groupBox_19)
        self.rB_splineOk.setObjectName(_fromUtf8("rB_splineOk"))
        self.gridLayout_8.addWidget(self.rB_splineOk, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_19)
        self.groupBox_20 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_30 = QtGui.QLabel(self.groupBox_20)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_14.addWidget(self.label_30)
        self.rMedFiltS = QtGui.QSpinBox(self.groupBox_20)
        self.rMedFiltS.setMinimum(1)
        self.rMedFiltS.setSingleStep(2)
        self.rMedFiltS.setProperty("value", 3)
        self.rMedFiltS.setObjectName(_fromUtf8("rMedFiltS"))
        self.horizontalLayout_14.addWidget(self.rMedFiltS)
        self.rMedFilt = QtGui.QPushButton(self.groupBox_20)
        self.rMedFilt.setObjectName(_fromUtf8("rMedFilt"))
        self.horizontalLayout_14.addWidget(self.rMedFilt)
        self.verticalLayout_5.addWidget(self.groupBox_20)
        self.groupBox_16 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_16)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.typeExp = QtGui.QComboBox(self.groupBox_16)
        self.typeExp.setObjectName(_fromUtf8("typeExp"))
        self.typeExp.addItem(_fromUtf8(""))
        self.typeExp.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.typeExp, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_16)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.calibr = QtGui.QLineEdit(self.groupBox_16)
        self.calibr.setObjectName(_fromUtf8("calibr"))
        self.gridLayout_5.addWidget(self.calibr, 1, 1, 1, 1)
        self.recalcCalibr = QtGui.QPushButton(self.groupBox_16)
        self.recalcCalibr.setObjectName(_fromUtf8("recalcCalibr"))
        self.gridLayout_5.addWidget(self.recalcCalibr, 2, 0, 1, 1)
        self.recalcForIntens = QtGui.QPushButton(self.groupBox_16)
        self.recalcForIntens.setObjectName(_fromUtf8("recalcForIntens"))
        self.gridLayout_5.addWidget(self.recalcForIntens, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_16)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.rPlot = QtGui.QPushButton(self.tab_4)
        self.rPlot.setObjectName(_fromUtf8("rPlot"))
        self.horizontalLayout_10.addWidget(self.rPlot)
        self.rSave = QtGui.QPushButton(self.tab_4)
        self.rSave.setObjectName(_fromUtf8("rSave"))
        self.horizontalLayout_10.addWidget(self.rSave)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QTR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.cPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.cFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cMCheck.setText(QtGui.QApplication.translate("MainWindow", "Множник", None, QtGui.QApplication.UnicodeUTF8))
        self.cFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.cLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.sPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.sFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.sFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sMCheck.setText(QtGui.QApplication.translate("MainWindow", "Множник", None, QtGui.QApplication.UnicodeUTF8))
        self.sLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Додаткові параметри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Довжина хвилі: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LENGTH.setText(QtGui.QApplication.translate("MainWindow", "1064", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Вхідні дані", None, QtGui.QApplication.UnicodeUTF8))
        self.cReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.cUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.cY_XScale.setText(QtGui.QApplication.translate("MainWindow", "Y/X", None, QtGui.QApplication.UnicodeUTF8))
        self.cLogScale.setTitle(QtGui.QApplication.translate("MainWindow", "Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.cXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.cYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Межі", None, QtGui.QApplication.UnicodeUTF8))
        self.cAllSliceConcat.setItemText(0, QtGui.QApplication.translate("MainWindow", "Увесь діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.cAllSliceConcat.setItemText(1, QtGui.QApplication.translate("MainWindow", "Вирізати", None, QtGui.QApplication.UnicodeUTF8))
        self.cAllSliceConcat.setItemText(2, QtGui.QApplication.translate("MainWindow", "Обробити частину", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Кількість вузлів", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyP.setToolTip(QtGui.QApplication.translate("MainWindow", "Відсоток від максимального відхилення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyN.setToolTip(QtGui.QApplication.translate("MainWindow", "Розмір порцій, для яких буде проводитись обробка", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.cAverageStep.setToolTip(QtGui.QApplication.translate("MainWindow", "Розмір порцій, для яких буде проводитись усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.cAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.cAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра:", None, QtGui.QApplication.UnicodeUTF8))
        self.cMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.cSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.sReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.sUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.sY_XScale.setText(QtGui.QApplication.translate("MainWindow", "Y/X", None, QtGui.QApplication.UnicodeUTF8))
        self.sLogScale.setTitle(QtGui.QApplication.translate("MainWindow", "Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.sYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Межі", None, QtGui.QApplication.UnicodeUTF8))
        self.sAllSliceConcat.setItemText(0, QtGui.QApplication.translate("MainWindow", "Увесь діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.sAllSliceConcat.setItemText(1, QtGui.QApplication.translate("MainWindow", "Вирізати", None, QtGui.QApplication.UnicodeUTF8))
        self.sAllSliceConcat.setItemText(2, QtGui.QApplication.translate("MainWindow", "Обробити частину", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Кількість вузлів", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.sPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.sAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.sAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.sB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра:", None, QtGui.QApplication.UnicodeUTF8))
        self.sMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.sSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.rButton.setText(QtGui.QApplication.translate("MainWindow", "Обчислити", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(0, QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(1, QtGui.QApplication.translate("MainWindow", "nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(2, QtGui.QApplication.translate("MainWindow", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.rReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.rUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("MainWindow", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.rY_XScale.setText(QtGui.QApplication.translate("MainWindow", "Y_X", None, QtGui.QApplication.UnicodeUTF8))
        self.rLogScale.setTitle(QtGui.QApplication.translate("MainWindow", "Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.rXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.rYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("MainWindow", "Межі", None, QtGui.QApplication.UnicodeUTF8))
        self.rAllSliceConcat.setItemText(0, QtGui.QApplication.translate("MainWindow", "Увесь діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.rAllSliceConcat.setItemText(1, QtGui.QApplication.translate("MainWindow", "Вирізати", None, QtGui.QApplication.UnicodeUTF8))
        self.rAllSliceConcat.setItemText(2, QtGui.QApplication.translate("MainWindow", "Обробити частину", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_19.setTitle(QtGui.QApplication.translate("MainWindow", "B-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.rAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.rB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_20.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра", None, QtGui.QApplication.UnicodeUTF8))
        self.rMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("MainWindow", "Інтенсивність", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Тип експерименту:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeExp.setItemText(0, QtGui.QApplication.translate("MainWindow", "CW", None, QtGui.QApplication.UnicodeUTF8))
        self.typeExp.setItemText(1, QtGui.QApplication.translate("MainWindow", "PICO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Коефіцієнт калібровки:", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcCalibr.setText(QtGui.QApplication.translate("MainWindow", "Обчислити коеф. калібр.", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcForIntens.setText(QtGui.QApplication.translate("MainWindow", "Інтенсивність", None, QtGui.QApplication.UnicodeUTF8))
        self.rPlot.setText(QtGui.QApplication.translate("MainWindow", "Побудувати", None, QtGui.QApplication.UnicodeUTF8))
        self.rSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Результат", None, QtGui.QApplication.UnicodeUTF8))

