# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Mon Nov 19 13:38:10 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 620)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 620))
        MainWindow.setMaximumSize(QtCore.QSize(500, 620))
        MainWindow.setBaseSize(QtCore.QSize(500, 620))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 500, 600))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.tabWidget.setBaseSize(QtCore.QSize(500, 600))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_1)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1, 1, 381, 451))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.label_32 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_7.addWidget(self.label_32)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cPath = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.cPath.setText(_fromUtf8(""))
        self.cPath.setObjectName(_fromUtf8("cPath"))
        self.horizontalLayout.addWidget(self.cPath)
        self.cFile = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.cFile.setObjectName(_fromUtf8("cFile"))
        self.horizontalLayout.addWidget(self.cFile)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cYColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.cYColumn.setMinimum(0)
        self.cYColumn.setMaximum(100)
        self.cYColumn.setProperty("value", 4)
        self.cYColumn.setObjectName(_fromUtf8("cYColumn"))
        self.gridLayout_2.addWidget(self.cYColumn, 1, 1, 1, 1)
        self.cMColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.cMColumn.setMinimum(0)
        self.cMColumn.setMaximum(100)
        self.cMColumn.setProperty("value", 1)
        self.cMColumn.setObjectName(_fromUtf8("cMColumn"))
        self.gridLayout_2.addWidget(self.cMColumn, 1, 3, 1, 1)
        self.cXColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.cXColumn.setMinimum(0)
        self.cXColumn.setMaximum(100)
        self.cXColumn.setProperty("value", 5)
        self.cXColumn.setObjectName(_fromUtf8("cXColumn"))
        self.gridLayout_2.addWidget(self.cXColumn, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.cMCheck = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.cMCheck.setEnabled(True)
        self.cMCheck.setCheckable(True)
        self.cMCheck.setChecked(True)
        self.cMCheck.setTristate(False)
        self.cMCheck.setObjectName(_fromUtf8("cMCheck"))
        self.gridLayout_2.addWidget(self.cMCheck, 0, 3, 1, 1)
        self.cXFilt = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.cXFilt.setEnabled(False)
        self.cXFilt.setObjectName(_fromUtf8("cXFilt"))
        self.gridLayout_2.addWidget(self.cXFilt, 2, 0, 1, 1)
        self.cYFilt = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.cYFilt.setEnabled(False)
        self.cYFilt.setObjectName(_fromUtf8("cYFilt"))
        self.gridLayout_2.addWidget(self.cYFilt, 2, 1, 1, 1)
        self.cFilt = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.cFilt.setObjectName(_fromUtf8("cFilt"))
        self.gridLayout_2.addWidget(self.cFilt, 2, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.cLoad = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.cLoad.setEnabled(False)
        self.cLoad.setObjectName(_fromUtf8("cLoad"))
        self.verticalLayout_7.addWidget(self.cLoad)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.label_33 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_7.addWidget(self.label_33)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sPath = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.sPath.setText(_fromUtf8(""))
        self.sPath.setObjectName(_fromUtf8("sPath"))
        self.horizontalLayout_2.addWidget(self.sPath)
        self.sFile = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.sFile.setObjectName(_fromUtf8("sFile"))
        self.horizontalLayout_2.addWidget(self.sFile)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.sFilt = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.sFilt.setObjectName(_fromUtf8("sFilt"))
        self.gridLayout_4.addWidget(self.sFilt, 2, 3, 1, 1)
        self.sXFilt = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.sXFilt.setEnabled(False)
        self.sXFilt.setObjectName(_fromUtf8("sXFilt"))
        self.gridLayout_4.addWidget(self.sXFilt, 2, 0, 1, 1)
        self.sYFilt = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.sYFilt.setEnabled(False)
        self.sYFilt.setObjectName(_fromUtf8("sYFilt"))
        self.gridLayout_4.addWidget(self.sYFilt, 2, 1, 1, 1)
        self.sMColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.sMColumn.setMinimum(0)
        self.sMColumn.setMaximum(100)
        self.sMColumn.setProperty("value", 1)
        self.sMColumn.setObjectName(_fromUtf8("sMColumn"))
        self.gridLayout_4.addWidget(self.sMColumn, 1, 3, 1, 1)
        self.sYColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.sYColumn.setMinimum(0)
        self.sYColumn.setMaximum(100)
        self.sYColumn.setProperty("value", 4)
        self.sYColumn.setObjectName(_fromUtf8("sYColumn"))
        self.gridLayout_4.addWidget(self.sYColumn, 1, 1, 1, 1)
        self.sXColumn = QtGui.QSpinBox(self.verticalLayoutWidget_5)
        self.sXColumn.setMinimum(0)
        self.sXColumn.setMaximum(100)
        self.sXColumn.setProperty("value", 5)
        self.sXColumn.setObjectName(_fromUtf8("sXColumn"))
        self.gridLayout_4.addWidget(self.sXColumn, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.sMCheck = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.sMCheck.setEnabled(True)
        self.sMCheck.setCheckable(True)
        self.sMCheck.setChecked(True)
        self.sMCheck.setTristate(False)
        self.sMCheck.setObjectName(_fromUtf8("sMCheck"))
        self.gridLayout_4.addWidget(self.sMCheck, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.sLoad = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.sLoad.setEnabled(False)
        self.sLoad.setObjectName(_fromUtf8("sLoad"))
        self.verticalLayout_7.addWidget(self.sLoad)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_17.addWidget(self.label_37)
        self.LENGTH = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.LENGTH.setObjectName(_fromUtf8("LENGTH"))
        self.horizontalLayout_17.addWidget(self.LENGTH)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 431, 522))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cReset = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cReset.setEnabled(False)
        self.cReset.setObjectName(_fromUtf8("cReset"))
        self.horizontalLayout_7.addWidget(self.cReset)
        self.cUndo = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cUndo.setEnabled(False)
        self.cUndo.setObjectName(_fromUtf8("cUndo"))
        self.horizontalLayout_7.addWidget(self.cUndo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.cLogScale = QtGui.QHBoxLayout()
        self.cLogScale.setObjectName(_fromUtf8("cLogScale"))
        self.label_34 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cLogScale.addWidget(self.label_34)
        self.cXLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.cXLogScale.setObjectName(_fromUtf8("cXLogScale"))
        self.cLogScale.addWidget(self.cXLogScale)
        self.cYLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.cYLogScale.setObjectName(_fromUtf8("cYLogScale"))
        self.cLogScale.addWidget(self.cYLogScale)
        self.verticalLayout_2.addLayout(self.cLogScale)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 1, 1, 1)
        self.cPolyM = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        self.cPolyM.setMinimum(1)
        self.cPolyM.setMaximum(20)
        self.cPolyM.setProperty("value", 6)
        self.cPolyM.setObjectName(_fromUtf8("cPolyM"))
        self.gridLayout_6.addWidget(self.cPolyM, 1, 2, 1, 1)
        self.cPolyD = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cPolyD.setDecimals(3)
        self.cPolyD.setMinimum(0.001)
        self.cPolyD.setMaximum(999.0)
        self.cPolyD.setSingleStep(0.01)
        self.cPolyD.setProperty("value", 0.7)
        self.cPolyD.setObjectName(_fromUtf8("cPolyD"))
        self.gridLayout_6.addWidget(self.cPolyD, 1, 1, 1, 1)
        self.cPolyP = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cPolyP.setDecimals(3)
        self.cPolyP.setMinimum(0.001)
        self.cPolyP.setMaximum(9999.0)
        self.cPolyP.setProperty("value", 80.0)
        self.cPolyP.setObjectName(_fromUtf8("cPolyP"))
        self.gridLayout_6.addWidget(self.cPolyP, 1, 0, 1, 1)
        self.cPolyOk = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cPolyOk.setObjectName(_fromUtf8("cPolyOk"))
        self.gridLayout_6.addWidget(self.cPolyOk, 2, 2, 1, 1)
        self.cAutoPoly = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.cAutoPoly.setChecked(True)
        self.cAutoPoly.setObjectName(_fromUtf8("cAutoPoly"))
        self.gridLayout_6.addWidget(self.cAutoPoly, 2, 0, 1, 1)
        self.cPolyPrecision = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cPolyPrecision.setDecimals(3)
        self.cPolyPrecision.setMinimum(0.001)
        self.cPolyPrecision.setMaximum(1.0)
        self.cPolyPrecision.setSingleStep(0.05)
        self.cPolyPrecision.setProperty("value", 0.8)
        self.cPolyPrecision.setObjectName(_fromUtf8("cPolyPrecision"))
        self.gridLayout_6.addWidget(self.cPolyPrecision, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cAutoInterval = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.cAutoInterval.setChecked(False)
        self.cAutoInterval.setObjectName(_fromUtf8("cAutoInterval"))
        self.horizontalLayout_9.addWidget(self.cAutoInterval)
        self.cStart = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cStart.setMinimum(0.01)
        self.cStart.setMaximum(99999999.0)
        self.cStart.setSingleStep(0.5)
        self.cStart.setProperty("value", 0.01)
        self.cStart.setObjectName(_fromUtf8("cStart"))
        self.horizontalLayout_9.addWidget(self.cStart)
        self.cEnd = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cEnd.setMinimum(0.01)
        self.cEnd.setMaximum(9999999.0)
        self.cEnd.setSingleStep(0.5)
        self.cEnd.setProperty("value", 0.01)
        self.cEnd.setObjectName(_fromUtf8("cEnd"))
        self.horizontalLayout_9.addWidget(self.cEnd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cAverageOk = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cAverageOk.setObjectName(_fromUtf8("cAverageOk"))
        self.gridLayout.addWidget(self.cAverageOk, 3, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 1, 1, 1)
        self.cAverageStep = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cAverageStep.setDecimals(4)
        self.cAverageStep.setMinimum(0.0001)
        self.cAverageStep.setMaximum(999999999.0)
        self.cAverageStep.setSingleStep(1e-06)
        self.cAverageStep.setProperty("value", 1.0)
        self.cAverageStep.setObjectName(_fromUtf8("cAverageStep"))
        self.gridLayout.addWidget(self.cAverageStep, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 2, 1, 1)
        self.cB_splineS = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cB_splineS.setDecimals(4)
        self.cB_splineS.setMinimum(0.0)
        self.cB_splineS.setMaximum(999999999.0)
        self.cB_splineS.setSingleStep(0.05)
        self.cB_splineS.setProperty("value", 1500000.0)
        self.cB_splineS.setObjectName(_fromUtf8("cB_splineS"))
        self.gridLayout_7.addWidget(self.cB_splineS, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 1, 1, 1)
        self.cB_splineOk = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cB_splineOk.setObjectName(_fromUtf8("cB_splineOk"))
        self.gridLayout_7.addWidget(self.cB_splineOk, 2, 3, 1, 1)
        self.cB_splineK = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        self.cB_splineK.setMinimum(1)
        self.cB_splineK.setMaximum(5)
        self.cB_splineK.setProperty("value", 3)
        self.cB_splineK.setObjectName(_fromUtf8("cB_splineK"))
        self.gridLayout_7.addWidget(self.cB_splineK, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 3, 1, 1)
        self.cB_splineStep = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.cB_splineStep.setDecimals(3)
        self.cB_splineStep.setMinimum(0.001)
        self.cB_splineStep.setMaximum(999999999.0)
        self.cB_splineStep.setSingleStep(0.5)
        self.cB_splineStep.setProperty("value", 1.0)
        self.cB_splineStep.setObjectName(_fromUtf8("cB_splineStep"))
        self.gridLayout_7.addWidget(self.cB_splineStep, 1, 1, 1, 1)
        self.cAutoB_splineS = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.cAutoB_splineS.setObjectName(_fromUtf8("cAutoB_splineS"))
        self.gridLayout_7.addWidget(self.cAutoB_splineS, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_2.addWidget(self.label_29)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.cMedFiltS = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        self.cMedFiltS.setMinimum(1)
        self.cMedFiltS.setSingleStep(2)
        self.cMedFiltS.setProperty("value", 3)
        self.cMedFiltS.setObjectName(_fromUtf8("cMedFiltS"))
        self.horizontalLayout_12.addWidget(self.cMedFiltS)
        self.cMedFilt = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cMedFilt.setObjectName(_fromUtf8("cMedFilt"))
        self.horizontalLayout_12.addWidget(self.cMedFilt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cSave = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cSave.setObjectName(_fromUtf8("cSave"))
        self.horizontalLayout_5.addWidget(self.cSave)
        self.cPlot = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.cPlot.setObjectName(_fromUtf8("cPlot"))
        self.horizontalLayout_5.addWidget(self.cPlot)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setEnabled(False)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 431, 521))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.sReset = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sReset.setEnabled(False)
        self.sReset.setObjectName(_fromUtf8("sReset"))
        self.horizontalLayout_8.addWidget(self.sReset)
        self.sUndo = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sUndo.setEnabled(False)
        self.sUndo.setObjectName(_fromUtf8("sUndo"))
        self.horizontalLayout_8.addWidget(self.sUndo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.sLogScale = QtGui.QHBoxLayout()
        self.sLogScale.setObjectName(_fromUtf8("sLogScale"))
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.sLogScale.addWidget(self.label_35)
        self.sXLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.sXLogScale.setObjectName(_fromUtf8("sXLogScale"))
        self.sLogScale.addWidget(self.sXLogScale)
        self.sYLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.sYLogScale.setObjectName(_fromUtf8("sYLogScale"))
        self.sLogScale.addWidget(self.sYLogScale)
        self.verticalLayout_4.addLayout(self.sLogScale)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_4.addWidget(self.label_19)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 0, 2, 1, 1)
        self.sPolyM = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.sPolyM.setMinimum(1)
        self.sPolyM.setMaximum(20)
        self.sPolyM.setProperty("value", 6)
        self.sPolyM.setObjectName(_fromUtf8("sPolyM"))
        self.gridLayout_8.addWidget(self.sPolyM, 1, 2, 1, 1)
        self.sPolyD = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sPolyD.setDecimals(3)
        self.sPolyD.setMinimum(0.001)
        self.sPolyD.setMaximum(999.0)
        self.sPolyD.setSingleStep(0.01)
        self.sPolyD.setProperty("value", 0.7)
        self.sPolyD.setObjectName(_fromUtf8("sPolyD"))
        self.gridLayout_8.addWidget(self.sPolyD, 1, 1, 1, 1)
        self.sPolyP = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sPolyP.setDecimals(3)
        self.sPolyP.setMinimum(0.001)
        self.sPolyP.setMaximum(9999.0)
        self.sPolyP.setProperty("value", 80.0)
        self.sPolyP.setObjectName(_fromUtf8("sPolyP"))
        self.gridLayout_8.addWidget(self.sPolyP, 1, 0, 1, 1)
        self.sPolyOk = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sPolyOk.setObjectName(_fromUtf8("sPolyOk"))
        self.gridLayout_8.addWidget(self.sPolyOk, 2, 2, 1, 1)
        self.sPolyPrecision = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sPolyPrecision.setDecimals(3)
        self.sPolyPrecision.setMinimum(0.001)
        self.sPolyPrecision.setMaximum(1.0)
        self.sPolyPrecision.setSingleStep(0.05)
        self.sPolyPrecision.setProperty("value", 0.8)
        self.sPolyPrecision.setObjectName(_fromUtf8("sPolyPrecision"))
        self.gridLayout_8.addWidget(self.sPolyPrecision, 2, 1, 1, 1)
        self.sAutoPoly = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.sAutoPoly.setChecked(True)
        self.sAutoPoly.setObjectName(_fromUtf8("sAutoPoly"))
        self.gridLayout_8.addWidget(self.sAutoPoly, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.sAutoInterval = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.sAutoInterval.setChecked(False)
        self.sAutoInterval.setObjectName(_fromUtf8("sAutoInterval"))
        self.horizontalLayout_15.addWidget(self.sAutoInterval)
        self.sStart = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sStart.setMinimum(0.01)
        self.sStart.setMaximum(9999999.0)
        self.sStart.setSingleStep(0.5)
        self.sStart.setObjectName(_fromUtf8("sStart"))
        self.horizontalLayout_15.addWidget(self.sStart)
        self.sEnd = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sEnd.setMinimum(0.01)
        self.sEnd.setMaximum(9999999.0)
        self.sEnd.setSingleStep(0.5)
        self.sEnd.setProperty("value", 0.01)
        self.sEnd.setObjectName(_fromUtf8("sEnd"))
        self.horizontalLayout_15.addWidget(self.sEnd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_4.addWidget(self.label_24)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.sAverageOk = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sAverageOk.setObjectName(_fromUtf8("sAverageOk"))
        self.gridLayout_9.addWidget(self.sAverageOk, 3, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 2, 1, 1, 1)
        self.sAverageStep = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sAverageStep.setDecimals(4)
        self.sAverageStep.setMinimum(0.001)
        self.sAverageStep.setMaximum(99999.0)
        self.sAverageStep.setSingleStep(0.5)
        self.sAverageStep.setProperty("value", 1.0)
        self.sAverageStep.setObjectName(_fromUtf8("sAverageStep"))
        self.gridLayout_9.addWidget(self.sAverageStep, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_9)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_4.addWidget(self.label_26)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.sB_splineK = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.sB_splineK.setMinimum(1)
        self.sB_splineK.setMaximum(5)
        self.sB_splineK.setProperty("value", 3)
        self.sB_splineK.setObjectName(_fromUtf8("sB_splineK"))
        self.gridLayout_10.addWidget(self.sB_splineK, 1, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_10.addWidget(self.label_27, 0, 2, 1, 1)
        self.sB_splineS = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sB_splineS.setDecimals(4)
        self.sB_splineS.setMinimum(0.0)
        self.sB_splineS.setMaximum(999999999.0)
        self.sB_splineS.setSingleStep(0.05)
        self.sB_splineS.setProperty("value", 1500000.0)
        self.sB_splineS.setObjectName(_fromUtf8("sB_splineS"))
        self.gridLayout_10.addWidget(self.sB_splineS, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_10.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 0, 3, 1, 1)
        self.sB_splineOk = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sB_splineOk.setObjectName(_fromUtf8("sB_splineOk"))
        self.gridLayout_10.addWidget(self.sB_splineOk, 2, 3, 1, 1)
        self.sB_splineStep = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.sB_splineStep.setDecimals(3)
        self.sB_splineStep.setMinimum(0.001)
        self.sB_splineStep.setMaximum(999999.0)
        self.sB_splineStep.setSingleStep(0.5)
        self.sB_splineStep.setProperty("value", 1.0)
        self.sB_splineStep.setObjectName(_fromUtf8("sB_splineStep"))
        self.gridLayout_10.addWidget(self.sB_splineStep, 1, 1, 1, 1)
        self.sAutoB_splineS = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.sAutoB_splineS.setObjectName(_fromUtf8("sAutoB_splineS"))
        self.gridLayout_10.addWidget(self.sAutoB_splineS, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_10)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_3.addWidget(self.label_23)
        self.sMedFiltS = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.sMedFiltS.setMinimum(1)
        self.sMedFiltS.setSingleStep(2)
        self.sMedFiltS.setProperty("value", 3)
        self.sMedFiltS.setObjectName(_fromUtf8("sMedFiltS"))
        self.horizontalLayout_3.addWidget(self.sMedFiltS)
        self.sMedFilt = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sMedFilt.setObjectName(_fromUtf8("sMedFilt"))
        self.horizontalLayout_3.addWidget(self.sMedFilt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.sSave = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sSave.setObjectName(_fromUtf8("sSave"))
        self.horizontalLayout_6.addWidget(self.sSave)
        self.sPlot = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.sPlot.setObjectName(_fromUtf8("sPlot"))
        self.horizontalLayout_6.addWidget(self.sPlot)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(False)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 431, 332))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.rButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rButton.setObjectName(_fromUtf8("rButton"))
        self.horizontalLayout_11.addWidget(self.rButton)
        self.rReset = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rReset.setEnabled(False)
        self.rReset.setObjectName(_fromUtf8("rReset"))
        self.horizontalLayout_11.addWidget(self.rReset)
        self.rUndo = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rUndo.setEnabled(False)
        self.rUndo.setObjectName(_fromUtf8("rUndo"))
        self.horizontalLayout_11.addWidget(self.rUndo)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.sLogScale_2 = QtGui.QHBoxLayout()
        self.sLogScale_2.setObjectName(_fromUtf8("sLogScale_2"))
        self.label_36 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.sLogScale_2.addWidget(self.label_36)
        self.rXLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.rXLogScale.setObjectName(_fromUtf8("rXLogScale"))
        self.sLogScale_2.addWidget(self.rXLogScale)
        self.rYLogScale = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.rYLogScale.setObjectName(_fromUtf8("rYLogScale"))
        self.sLogScale_2.addWidget(self.rYLogScale)
        self.verticalLayout.addLayout(self.sLogScale_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.rAutoInterval = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.rAutoInterval.setChecked(False)
        self.rAutoInterval.setObjectName(_fromUtf8("rAutoInterval"))
        self.horizontalLayout_16.addWidget(self.rAutoInterval)
        self.rStart = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.rStart.setMinimum(0.01)
        self.rStart.setMaximum(9999999.0)
        self.rStart.setSingleStep(0.5)
        self.rStart.setObjectName(_fromUtf8("rStart"))
        self.horizontalLayout_16.addWidget(self.rStart)
        self.rEnd = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.rEnd.setMinimum(0.01)
        self.rEnd.setMaximum(9999999.0)
        self.rEnd.setSingleStep(0.5)
        self.rEnd.setObjectName(_fromUtf8("rEnd"))
        self.horizontalLayout_16.addWidget(self.rEnd)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.label_51 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.verticalLayout.addWidget(self.label_51)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_17.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_49 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_17.addWidget(self.label_49, 0, 2, 1, 1)
        self.rB_splineS = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.rB_splineS.setDecimals(4)
        self.rB_splineS.setMinimum(0.0)
        self.rB_splineS.setMaximum(999999999.0)
        self.rB_splineS.setSingleStep(0.01)
        self.rB_splineS.setProperty("value", 10.0)
        self.rB_splineS.setObjectName(_fromUtf8("rB_splineS"))
        self.gridLayout_17.addWidget(self.rB_splineS, 1, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_17.addWidget(self.label_50, 0, 1, 1, 1)
        self.rB_splineK = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.rB_splineK.setMinimum(1)
        self.rB_splineK.setMaximum(5)
        self.rB_splineK.setProperty("value", 5)
        self.rB_splineK.setObjectName(_fromUtf8("rB_splineK"))
        self.gridLayout_17.addWidget(self.rB_splineK, 1, 3, 1, 1)
        self.rB_splineOk = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rB_splineOk.setObjectName(_fromUtf8("rB_splineOk"))
        self.gridLayout_17.addWidget(self.rB_splineOk, 2, 3, 1, 1)
        self.rB_splineStep = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.rB_splineStep.setDecimals(4)
        self.rB_splineStep.setMinimum(0.001)
        self.rB_splineStep.setMaximum(99999.0)
        self.rB_splineStep.setSingleStep(0.5)
        self.rB_splineStep.setProperty("value", 1.0)
        self.rB_splineStep.setObjectName(_fromUtf8("rB_splineStep"))
        self.gridLayout_17.addWidget(self.rB_splineStep, 1, 1, 1, 1)
        self.rAutoB_splineS = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.rAutoB_splineS.setObjectName(_fromUtf8("rAutoB_splineS"))
        self.gridLayout_17.addWidget(self.rAutoB_splineS, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_17)
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout.addWidget(self.label_31)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_14.addWidget(self.label_30)
        self.rMedFiltS = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.rMedFiltS.setMinimum(1)
        self.rMedFiltS.setSingleStep(2)
        self.rMedFiltS.setProperty("value", 3)
        self.rMedFiltS.setObjectName(_fromUtf8("rMedFiltS"))
        self.horizontalLayout_14.addWidget(self.rMedFiltS)
        self.rMedFilt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rMedFilt.setObjectName(_fromUtf8("rMedFilt"))
        self.horizontalLayout_14.addWidget(self.rMedFilt)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.rPlot = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rPlot.setObjectName(_fromUtf8("rPlot"))
        self.horizontalLayout_10.addWidget(self.rPlot)
        self.rSave = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.rSave.setObjectName(_fromUtf8("rSave"))
        self.horizontalLayout_10.addWidget(self.rSave)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.Close = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.verticalLayout.addWidget(self.Close)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QTR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.cPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.cFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cMCheck.setText(QtGui.QApplication.translate("MainWindow", "Множник", None, QtGui.QApplication.UnicodeUTF8))
        self.cFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.cLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.sPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.sFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.sFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sMCheck.setText(QtGui.QApplication.translate("MainWindow", "Множник", None, QtGui.QApplication.UnicodeUTF8))
        self.sLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Довжина хвилі", None, QtGui.QApplication.UnicodeUTF8))
        self.LENGTH.setText(QtGui.QApplication.translate("MainWindow", "1064", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Вхідні дані", None, QtGui.QApplication.UnicodeUTF8))
        self.cReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.cUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "log масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.cXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.cYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Ширина", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Коеф. уширення", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.cAutoPoly.setText(QtGui.QApplication.translate("MainWindow", "Авто", None, QtGui.QApplication.UnicodeUTF8))
        self.cAutoInterval.setText(QtGui.QApplication.translate("MainWindow", "авто межі", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.cAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.cAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра:", None, QtGui.QApplication.UnicodeUTF8))
        self.cMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.cSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.cPlot.setText(QtGui.QApplication.translate("MainWindow", "Побудувати", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.sReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.sUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "log масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.sXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.sYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Ширина", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Коеф. уширення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.sPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.sAutoPoly.setText(QtGui.QApplication.translate("MainWindow", "Авто", None, QtGui.QApplication.UnicodeUTF8))
        self.sAutoInterval.setText(QtGui.QApplication.translate("MainWindow", "авто межі", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.sAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.sB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.sAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра", None, QtGui.QApplication.UnicodeUTF8))
        self.sMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.sSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.sPlot.setText(QtGui.QApplication.translate("MainWindow", "Побудувати", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.rButton.setText(QtGui.QApplication.translate("MainWindow", "Обчислити", None, QtGui.QApplication.UnicodeUTF8))
        self.rReset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.rUndo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "log масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.rXLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.rYLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.rAutoInterval.setText(QtGui.QApplication.translate("MainWindow", "авто межі", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.rB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.rAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра", None, QtGui.QApplication.UnicodeUTF8))
        self.rMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.rPlot.setText(QtGui.QApplication.translate("MainWindow", "Побудувати", None, QtGui.QApplication.UnicodeUTF8))
        self.rSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("MainWindow", "Закрити", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Результат", None, QtGui.QApplication.UnicodeUTF8))

