# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 419)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setBaseSize(QtCore.QSize(900, 620))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(213, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 122, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 79, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 35, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(132, 132, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 140, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 122, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 79, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 35, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(132, 132, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 140, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 122, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(132, 132, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 140, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 68, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplWidget = QtWidgets.QHBoxLayout()
        self.mplWidget.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.mplWidget.setSpacing(1)
        self.mplWidget.setObjectName("mplWidget")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mplWidget.addItem(spacerItem)
        self.verticalLayout.addLayout(self.mplWidget)
        self.gridLayout.addWidget(self.horizontalWidget, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.namesTable = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.namesTable.sizePolicy().hasHeightForWidth())
        self.namesTable.setSizePolicy(sizePolicy)
        self.namesTable.setMaximumSize(QtCore.QSize(800, 60000))
        self.namesTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.namesTable.setDragEnabled(True)
        self.namesTable.setDragDropOverwriteMode(False)
        self.namesTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.namesTable.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.namesTable.setAlternatingRowColors(True)
        self.namesTable.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.namesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.namesTable.setColumnCount(4)
        self.namesTable.setObjectName("namesTable")
        self.namesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.namesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.namesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.namesTable.setHorizontalHeaderItem(2, item)
        self.namesTable.horizontalHeader().setVisible(False)
        self.namesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.namesTable.horizontalHeader().setMinimumSectionSize(15)
        self.namesTable.horizontalHeader().setSortIndicatorShown(False)
        self.namesTable.horizontalHeader().setStretchLastSection(True)
        self.namesTable.verticalHeader().setCascadingSectionResizes(True)
        self.namesTable.verticalHeader().setSortIndicatorShown(True)
        self.namesTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.namesTable)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.joinDataArrays = QtWidgets.QToolButton(self.tab)
        self.joinDataArrays.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.joinDataArrays.setObjectName("joinDataArrays")
        self.gridLayout_17.addWidget(self.joinDataArrays, 0, 5, 1, 1)
        self.multiPlot = QtWidgets.QToolButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("buttons/multiPlot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiPlot.setIcon(icon)
        self.multiPlot.setObjectName("multiPlot")
        self.gridLayout_17.addWidget(self.multiPlot, 0, 4, 1, 1)
        self.workWithSelectedData = QtWidgets.QCheckBox(self.tab)
        self.workWithSelectedData.setText("")
        self.workWithSelectedData.setObjectName("workWithSelectedData")
        self.gridLayout_17.addWidget(self.workWithSelectedData, 0, 6, 1, 1)
        self.rowMoveDown = QtWidgets.QToolButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("buttons/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rowMoveDown.setIcon(icon1)
        self.rowMoveDown.setObjectName("rowMoveDown")
        self.gridLayout_17.addWidget(self.rowMoveDown, 0, 2, 1, 1)
        self.deleteData = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteData.sizePolicy().hasHeightForWidth())
        self.deleteData.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("buttons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteData.setIcon(icon2)
        self.deleteData.setObjectName("deleteData")
        self.gridLayout_17.addWidget(self.deleteData, 0, 0, 1, 1)
        self.rowMoveUp = QtWidgets.QToolButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("buttons/up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rowMoveUp.setIcon(icon3)
        self.rowMoveUp.setObjectName("rowMoveUp")
        self.gridLayout_17.addWidget(self.rowMoveUp, 0, 3, 1, 1)
        self.saveData = QtWidgets.QToolButton(self.tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("buttons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveData.setIcon(icon4)
        self.saveData.setObjectName("saveData")
        self.gridLayout_17.addWidget(self.saveData, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_17)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputConsole = QtWidgets.QTextEdit(self.tab_2)
        self.outputConsole.setReadOnly(True)
        self.outputConsole.setObjectName("outputConsole")
        self.gridLayout_2.addWidget(self.outputConsole, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.activeTools = QtWidgets.QWidget(self.centralwidget)
        self.activeTools.setMinimumSize(QtCore.QSize(0, 50))
        self.activeTools.setObjectName("activeTools")
        self.gridLayout.addWidget(self.activeTools, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 669, 28))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_norm = QtWidgets.QMenu(self.menu_2)
        self.menu_norm.setTearOffEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("buttons/norm_On.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_norm.setIcon(icon5)
        self.menu_norm.setObjectName("menu_norm")
        self.menu_Scale = QtWidgets.QMenu(self.menu_2)
        self.menu_Scale.setObjectName("menu_Scale")
        self.mplactions = QtWidgets.QMenu(self.menu_2)
        self.mplactions.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("edit-cut")
        self.mplactions.setIcon(icon)
        self.mplactions.setObjectName("mplactions")
        self.menu_8 = QtWidgets.QMenu(self.menu_2)
        self.menu_8.setObjectName("menu_8")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_Hist = QtWidgets.QMenu(self.menuBar)
        self.menu_Hist.setObjectName("menu_Hist")
        self.menu_7 = QtWidgets.QMenu(self.menuBar)
        self.menu_7.setObjectName("menu_7")
        self.menu_5_ = QtWidgets.QMenu(self.menuBar)
        self.menu_5_.setObjectName("menu_5_")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBarGraph = QtWidgets.QToolBar(MainWindow)
        self.toolBarGraph.setAcceptDrops(False)
        self.toolBarGraph.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBarGraph.setFloatable(True)
        self.toolBarGraph.setObjectName("toolBarGraph")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarGraph)
        self.toolBarMpl = QtWidgets.QToolBar(MainWindow)
        self.toolBarMpl.setObjectName("toolBarMpl")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarMpl)
        self.toolBarScale = QtWidgets.QToolBar(MainWindow)
        self.toolBarScale.setObjectName("toolBarScale")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarScale)
        self.toolBarHistory = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBarHistory.sizePolicy().hasHeightForWidth())
        self.toolBarHistory.setSizePolicy(sizePolicy)
        self.toolBarHistory.setObjectName("toolBarHistory")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarHistory)
        self.instruments = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruments.sizePolicy().hasHeightForWidth())
        self.instruments.setSizePolicy(sizePolicy)
        self.instruments.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.instruments.setObjectName("instruments")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.instruments)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 214, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 178, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 214, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 178, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.toolBar.setPalette(palette)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.saveSettings = QtWidgets.QAction(MainWindow)
        self.saveSettings.setObjectName("saveSettings")
        self.loadSettings = QtWidgets.QAction(MainWindow)
        self.loadSettings.setObjectName("loadSettings")
        self.recalcIntens = QtWidgets.QAction(MainWindow)
        self.recalcIntens.setObjectName("recalcIntens")
        self.Discrete = QtWidgets.QAction(MainWindow)
        self.Discrete.setCheckable(True)
        self.Discrete.setObjectName("Discrete")
        self.Close = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("buttons/Reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon6)
        self.Close.setObjectName("Close")
        self.actionY_X = QtWidgets.QAction(MainWindow)
        self.actionY_X.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("buttons/Y_X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionY_X.setIcon(icon7)
        self.actionY_X.setObjectName("actionY_X")
        self.actionX_Log10 = QtWidgets.QAction(MainWindow)
        self.actionX_Log10.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("buttons/LgX.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionX_Log10.setIcon(icon8)
        self.actionX_Log10.setObjectName("actionX_Log10")
        self.actionY_Log10 = QtWidgets.QAction(MainWindow)
        self.actionY_Log10.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("buttons/LgY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionY_Log10.setIcon(icon9)
        self.actionY_Log10.setObjectName("actionY_Log10")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setEnabled(False)
        self.action_5.setObjectName("action_5")
        self.processAll = QtWidgets.QAction(MainWindow)
        self.processAll.setCheckable(True)
        self.processAll.setChecked(True)
        self.processAll.setObjectName("processAll")
        self.processView = QtWidgets.QAction(MainWindow)
        self.processView.setCheckable(True)
        self.processView.setObjectName("processView")
        self.Undo = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("buttons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Undo.setIcon(icon10)
        self.Undo.setMenuRole(QtWidgets.QAction.ApplicationSpecificRole)
        self.Undo.setObjectName("Undo")
        self.Reset = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("buttons/reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Reset.setIcon(icon11)
        self.Reset.setObjectName("Reset")
        self.norm_Max = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("buttons/norm_Max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_Max.setIcon(icon12)
        self.norm_Max.setObjectName("norm_Max")
        self.norm_Point = QtWidgets.QAction(MainWindow)
        self.norm_Point.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("buttons/norm_Point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_Point.setIcon(icon13)
        self.norm_Point.setObjectName("norm_Point")
        self.settings = QtWidgets.QAction(MainWindow)
        self.settings.setObjectName("settings")
        self.createProj = QtWidgets.QAction(MainWindow)
        self.createProj.setObjectName("createProj")
        self.norm_FirstPoint = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("buttons/norm_FirstPoint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_FirstPoint.setIcon(icon14)
        self.norm_FirstPoint.setObjectName("norm_FirstPoint")
        self.autoScale = QtWidgets.QAction(MainWindow)
        self.autoScale.setCheckable(True)
        self.autoScale.setChecked(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("buttons/Rescale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoScale.setIcon(icon15)
        self.autoScale.setObjectName("autoScale")
        self.tmpShow = QtWidgets.QAction(MainWindow)
        self.tmpShow.setCheckable(True)
        self.tmpShow.setChecked(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("buttons/ShowTmp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tmpShow.setIcon(icon16)
        self.tmpShow.setObjectName("tmpShow")
        self.mplactionCut_by_line = QtWidgets.QAction(MainWindow)
        self.mplactionCut_by_line.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("buttons/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mplactionCut_by_line.setIcon(icon17)
        self.mplactionCut_by_line.setObjectName("mplactionCut_by_line")
        self.mplactionCut_by_rect = QtWidgets.QAction(MainWindow)
        self.mplactionCut_by_rect.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("buttons/rect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mplactionCut_by_rect.setIcon(icon18)
        self.mplactionCut_by_rect.setObjectName("mplactionCut_by_rect")
        self.movePoint = QtWidgets.QAction(MainWindow)
        self.movePoint.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("buttons/movePoint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movePoint.setIcon(icon19)
        self.movePoint.setObjectName("movePoint")
        self.console = QtWidgets.QAction(MainWindow)
        self.console.setObjectName("console")
        self.actionAverageWindow = QtWidgets.QAction(MainWindow)
        self.actionAverageWindow.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("buttons/average.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAverageWindow.setIcon(icon20)
        self.actionAverageWindow.setObjectName("actionAverageWindow")
        self.actionFiltFilt = QtWidgets.QAction(MainWindow)
        self.actionFiltFilt.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("buttons/filtfilt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFiltFilt.setIcon(icon21)
        self.actionFiltFilt.setObjectName("actionFiltFilt")
        self.actionB_spline = QtWidgets.QAction(MainWindow)
        self.actionB_spline.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("buttons/b_spline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionB_spline.setIcon(icon22)
        self.actionB_spline.setObjectName("actionB_spline")
        self.actionPolyFit = QtWidgets.QAction(MainWindow)
        self.actionPolyFit.setCheckable(True)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("buttons/polyFit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyFit.setIcon(icon23)
        self.actionPolyFit.setObjectName("actionPolyFit")
        self.actionPolyCut = QtWidgets.QAction(MainWindow)
        self.actionPolyCut.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("buttons/polyCut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyCut.setIcon(icon24)
        self.actionPolyCut.setObjectName("actionPolyCut")
        self.actionOpenFiles = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("buttons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFiles.setIcon(icon25)
        self.actionOpenFiles.setObjectName("actionOpenFiles")
        self.actionDataLoad = QtWidgets.QAction(MainWindow)
        self.actionDataLoad.setCheckable(True)
        self.actionDataLoad.setChecked(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("buttons/selectData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDataLoad.setIcon(icon26)
        self.actionDataLoad.setObjectName("actionDataLoad")
        self.actionNormData = QtWidgets.QAction(MainWindow)
        self.actionNormData.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("buttons/normData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormData.setIcon(icon27)
        self.actionNormData.setObjectName("actionNormData")
        self.actionReChi3 = QtWidgets.QAction(MainWindow)
        self.actionReChi3.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("buttons/reHi3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReChi3.setIcon(icon28)
        self.actionReChi3.setObjectName("actionReChi3")
        self.actionFilters = QtWidgets.QAction(MainWindow)
        self.actionFilters.setCheckable(True)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("buttons/filters.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilters.setIcon(icon29)
        self.actionFilters.setObjectName("actionFilters")
        self.actionSaveData = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("filesave")
        self.actionSaveData.setIcon(icon)
        self.actionSaveData.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSaveData.setObjectName("actionSaveData")
        self.norm_Shift0 = QtWidgets.QAction(MainWindow)
        self.norm_Shift0.setObjectName("norm_Shift0")
        self.norm_Shift0X = QtWidgets.QAction(MainWindow)
        self.norm_Shift0X.setObjectName("norm_Shift0X")
        self.actionIntensCalibr = QtWidgets.QAction(MainWindow)
        self.actionIntensCalibr.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("buttons/Intens.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIntensCalibr.setIcon(icon30)
        self.actionIntensCalibr.setObjectName("actionIntensCalibr")
        self.actionProcessView = QtWidgets.QAction(MainWindow)
        self.actionProcessView.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("buttons/ViewProcess.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcessView.setIcon(icon31)
        self.actionProcessView.setObjectName("actionProcessView")
        self.norm_ShiftRange = QtWidgets.QAction(MainWindow)
        self.norm_ShiftRange.setCheckable(True)
        self.norm_ShiftRange.setObjectName("norm_ShiftRange")
        self.flipData = QtWidgets.QAction(MainWindow)
        self.flipData.setObjectName("flipData")
        self.actionImChi3 = QtWidgets.QAction(MainWindow)
        self.actionImChi3.setCheckable(True)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("buttons/ImHi3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImChi3.setIcon(icon32)
        self.actionImChi3.setObjectName("actionImChi3")
        self.actionDataDock = QtWidgets.QAction(MainWindow)
        self.actionDataDock.setObjectName("actionDataDock")
        self.norm_Shift0Xh = QtWidgets.QAction(MainWindow)
        self.norm_Shift0Xh.setCheckable(True)
        self.norm_Shift0Xh.setObjectName("norm_Shift0Xh")
        self.actionSaveProject = QtWidgets.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionSaveAll = QtWidgets.QAction(MainWindow)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionDelProjHistory = QtWidgets.QAction(MainWindow)
        self.actionDelProjHistory.setObjectName("actionDelProjHistory")
        self.norm_AtX = QtWidgets.QAction(MainWindow)
        self.norm_AtX.setObjectName("norm_AtX")
        self.loadSettingFromIni = QtWidgets.QAction(MainWindow)
        self.loadSettingFromIni.setCheckable(True)
        self.loadSettingFromIni.setObjectName("loadSettingFromIni")
        self.actionDublicateData = QtWidgets.QAction(MainWindow)
        self.actionDublicateData.setCheckable(False)
        self.actionDublicateData.setObjectName("actionDublicateData")
        self.action_find2Tangent = QtWidgets.QAction(MainWindow)
        self.action_find2Tangent.setCheckable(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("buttons/tan2p.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_find2Tangent.setIcon(icon33)
        self.action_find2Tangent.setObjectName("action_find2Tangent")
        self.action_ShowErrors = QtWidgets.QAction(MainWindow)
        self.action_ShowErrors.setCheckable(True)
        self.action_ShowErrors.setObjectName("action_ShowErrors")
        self.actionNormShift = QtWidgets.QAction(MainWindow)
        self.actionNormShift.setObjectName("actionNormShift")
        self.menu.addAction(self.settings)
        self.menu.addAction(self.loadSettingFromIni)
        self.menu_norm.addAction(self.norm_Max)
        self.menu_norm.addAction(self.norm_Point)
        self.menu_norm.addAction(self.norm_FirstPoint)
        self.menu_norm.addAction(self.norm_Shift0)
        self.menu_norm.addAction(self.norm_Shift0X)
        self.menu_norm.addAction(self.norm_ShiftRange)
        self.menu_norm.addAction(self.norm_Shift0Xh)
        self.menu_norm.addAction(self.norm_AtX)
        self.menu_Scale.addAction(self.actionY_Log10)
        self.menu_Scale.addAction(self.actionX_Log10)
        self.menu_Scale.addAction(self.actionY_X)
        self.mplactions.addAction(self.mplactionCut_by_line)
        self.mplactions.addAction(self.mplactionCut_by_rect)
        self.menu_8.addAction(self.actionFiltFilt)
        self.menu_2.addAction(self.recalcIntens)
        self.menu_2.addAction(self.actionFilters)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_Scale.menuAction())
        self.menu_2.addAction(self.autoScale)
        self.menu_2.addAction(self.tmpShow)
        self.menu_2.addAction(self.menu_norm.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.mplactions.menuAction())
        self.menu_2.addAction(self.movePoint)
        self.menu_2.addAction(self.menu_8.menuAction())
        self.menu_2.addAction(self.actionAverageWindow)
        self.menu_2.addAction(self.actionB_spline)
        self.menu_2.addAction(self.actionPolyFit)
        self.menu_2.addAction(self.actionPolyCut)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionNormData)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionReChi3)
        self.menu_2.addAction(self.actionImChi3)
        self.menu_2.addAction(self.flipData)
        self.menu_2.addAction(self.actionDublicateData)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.processView)
        self.menu_3.addAction(self.action_ShowErrors)
        self.menu_4.addAction(self.actionOpenFiles)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actionDataLoad)
        self.menu_4.addAction(self.actionSaveData)
        self.menu_4.addAction(self.Close)
        self.menu_4.addAction(self.actionSaveProject)
        self.menu_4.addAction(self.actionSaveAll)
        self.menu_4.addAction(self.actionOpenProject)
        self.menu_Hist.addAction(self.Undo)
        self.menu_Hist.addAction(self.Reset)
        self.menu_7.addAction(self.console)
        self.menu_7.addSeparator()
        self.menu_7.addAction(self.actionDataDock)
        self.menu_5_.addAction(self.actionDelProjHistory)
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_Hist.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_7.menuAction())
        self.menuBar.addAction(self.menu_5_.menuAction())
        self.toolBarGraph.addAction(self.autoScale)
        self.toolBarGraph.addAction(self.tmpShow)
        self.toolBarGraph.addAction(self.actionProcessView)
        self.toolBarGraph.addSeparator()
        self.toolBarMpl.addAction(self.mplactionCut_by_line)
        self.toolBarMpl.addAction(self.mplactionCut_by_rect)
        self.toolBarMpl.addAction(self.movePoint)
        self.toolBarMpl.addAction(self.action_find2Tangent)
        self.toolBarScale.addAction(self.actionY_X)
        self.toolBarScale.addAction(self.actionX_Log10)
        self.toolBarScale.addAction(self.actionY_Log10)
        self.toolBarHistory.addAction(self.Undo)
        self.toolBarHistory.addAction(self.Reset)
        self.instruments.addAction(self.actionDataLoad)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionPolyCut)
        self.instruments.addAction(self.actionPolyFit)
        self.instruments.addAction(self.actionB_spline)
        self.instruments.addAction(self.actionFiltFilt)
        self.instruments.addAction(self.actionAverageWindow)
        self.instruments.addAction(self.actionFilters)
        self.instruments.addAction(self.actionIntensCalibr)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionNormData)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionReChi3)
        self.instruments.addAction(self.actionImChi3)
        self.instruments.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QTR"))
        item = self.namesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Файл"))
        item = self.namesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "#"))
        item = self.namesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Color"))
        self.joinDataArrays.setToolTip(_translate("MainWindow", "Об’єднати дані"))
        self.joinDataArrays.setText(_translate("MainWindow", "+"))
        self.joinDataArrays.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.workWithSelectedData.setToolTip(_translate("MainWindow", "Застосовувати операції до обраних даних"))
        self.rowMoveDown.setText(_translate("MainWindow", "..."))
        self.deleteData.setText(_translate("MainWindow", "..."))
        self.rowMoveUp.setText(_translate("MainWindow", "..."))
        self.saveData.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu.setTitle(_translate("MainWindow", "Налаштування"))
        self.menu_2.setTitle(_translate("MainWindow", "Обробка"))
        self.menu_norm.setTitle(_translate("MainWindow", "Нормувати"))
        self.menu_Scale.setTitle(_translate("MainWindow", "Масштаб"))
        self.mplactions.setTitle(_translate("MainWindow", "Обрізка"))
        self.menu_8.setTitle(_translate("MainWindow", "Фільтри"))
        self.menu_3.setTitle(_translate("MainWindow", "Режим"))
        self.menu_4.setTitle(_translate("MainWindow", "Файл"))
        self.menu_Hist.setTitle(_translate("MainWindow", "Правка"))
        self.menu_7.setTitle(_translate("MainWindow", "Інструменти"))
        self.menu_5_.setTitle(_translate("MainWindow", "Проект"))
        self.toolBarGraph.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBarMpl.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBarScale.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBarHistory.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.instruments.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.saveSettings.setText(_translate("MainWindow", "зберегти"))
        self.loadSettings.setText(_translate("MainWindow", "завантажити"))
        self.recalcIntens.setText(_translate("MainWindow", "Посадити на інтенсивність"))
        self.recalcIntens.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.Discrete.setText(_translate("MainWindow", "Дискретний"))
        self.Discrete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.Close.setText(_translate("MainWindow", "Вийти"))
        self.Close.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionY_X.setText(_translate("MainWindow", "y -> Y/X"))
        self.actionX_Log10.setText(_translate("MainWindow", "&x -> Log10"))
        self.actionY_Log10.setText(_translate("MainWindow", "&y -> Log10"))
        self.action_5.setText(_translate("MainWindow", "Межі обробки:"))
        self.processAll.setText(_translate("MainWindow", "Все"))
        self.processView.setText(_translate("MainWindow", "Видимий діапазон"))
        self.Undo.setText(_translate("MainWindow", "Назад"))
        self.Undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.Reset.setText(_translate("MainWindow", "Скинути"))
        self.Reset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.norm_Max.setText(_translate("MainWindow", "Нормувати на максимум"))
        self.norm_Point.setText(_translate("MainWindow", "Нормувати на вказану точку"))
        self.settings.setText(_translate("MainWindow", "Параметри"))
        self.createProj.setText(_translate("MainWindow", "Створити"))
        self.norm_FirstPoint.setText(_translate("MainWindow", "Нормувати на першу точку"))
        self.autoScale.setText(_translate("MainWindow", "Автомасштабування"))
        self.tmpShow.setText(_translate("MainWindow", "Проміжні побудови"))
        self.mplactionCut_by_line.setText(_translate("MainWindow", "Лінією"))
        self.mplactionCut_by_rect.setText(_translate("MainWindow", "Прямокутником"))
        self.movePoint.setText(_translate("MainWindow", "Перемістити точки"))
        self.console.setText(_translate("MainWindow", "Консоль"))
        self.actionAverageWindow.setText(_translate("MainWindow", "&average"))
        self.actionFiltFilt.setText(_translate("MainWindow", "&filtfilt"))
        self.actionB_spline.setText(_translate("MainWindow", "&b-spline"))
        self.actionPolyFit.setText(_translate("MainWindow", "&polyFit"))
        self.actionPolyCut.setText(_translate("MainWindow", "p&olyCut"))
        self.actionOpenFiles.setText(_translate("MainWindow", "Відкрити файли"))
        self.actionDataLoad.setText(_translate("MainWindow", "вибрати дані"))
        self.actionDataLoad.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionNormData.setText(_translate("MainWindow", "Нормувати"))
        self.actionReChi3.setText(_translate("MainWindow", "Обчислити &Re(hi3)"))
        self.actionFilters.setText(_translate("MainWindow", "Посадити на фільтри"))
        self.actionSaveData.setText(_translate("MainWindow", "Зберегти"))
        self.actionSaveData.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.norm_Shift0.setText(_translate("MainWindow", "Змістити в НУЛЬ!!!!"))
        self.norm_Shift0X.setText(_translate("MainWindow", "Центрувати по &X"))
        self.actionIntensCalibr.setText(_translate("MainWindow", "Інтенсивність"))
        self.actionIntensCalibr.setToolTip(_translate("MainWindow", "Посадка на інтенсивність"))
        self.actionProcessView.setText(_translate("MainWindow", "Видимий"))
        self.actionProcessView.setToolTip(_translate("MainWindow", "Обробка видимого діапазону"))
        self.norm_ShiftRange.setText(_translate("MainWindow", "Змістити діапазон"))
        self.flipData.setText(_translate("MainWindow", "Розвернути"))
        self.actionImChi3.setText(_translate("MainWindow", "Обчислити &Im(hi3)"))
        self.actionDataDock.setText(_translate("MainWindow", "Панель даних"))
        self.norm_Shift0Xh.setText(_translate("MainWindow", "Центрувати по X вручну"))
        self.actionSaveProject.setText(_translate("MainWindow", "Зберегти проект"))
        self.actionSaveAll.setText(_translate("MainWindow", "Зберегти все"))
        self.actionOpenProject.setText(_translate("MainWindow", "Відкрити проект"))
        self.actionDelProjHistory.setText(_translate("MainWindow", "Очистити історію"))
        self.norm_AtX.setText(_translate("MainWindow", "нормувати в Х"))
        self.loadSettingFromIni.setText(_translate("MainWindow", "Завантажувати з попереднього"))
        self.actionDublicateData.setText(_translate("MainWindow", "Дублювати"))
        self.action_find2Tangent.setText(_translate("MainWindow", "Точка перегину"))
        self.action_find2Tangent.setToolTip(_translate("MainWindow", "Знайти точку перегин на кривій"))
        self.action_ShowErrors.setText(_translate("MainWindow", "Показувати похибки"))
        self.actionNormShift.setText(_translate("MainWindow", "S"))

