# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kronosua/work/QTR/ui/form.ui'
#
# Created: Sun Feb  3 18:16:29 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1006, 695)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(448, 695))
        MainWindow.setBaseSize(QtCore.QSize(900, 620))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.tabWidget.setBaseSize(QtCore.QSize(299, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab_1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cPath = QtGui.QLineEdit(self.groupBox)
        self.cPath.setText(_fromUtf8(""))
        self.cPath.setObjectName(_fromUtf8("cPath"))
        self.horizontalLayout.addWidget(self.cPath)
        self.cFile = QtGui.QPushButton(self.groupBox)
        self.cFile.setObjectName(_fromUtf8("cFile"))
        self.horizontalLayout.addWidget(self.cFile)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cYColumn = QtGui.QSpinBox(self.groupBox)
        self.cYColumn.setMinimum(0)
        self.cYColumn.setMaximum(100)
        self.cYColumn.setProperty("value", 3)
        self.cYColumn.setObjectName(_fromUtf8("cYColumn"))
        self.gridLayout_2.addWidget(self.cYColumn, 2, 1, 1, 1)
        self.cMColumn = QtGui.QSpinBox(self.groupBox)
        self.cMColumn.setMinimum(0)
        self.cMColumn.setMaximum(100)
        self.cMColumn.setProperty("value", 1)
        self.cMColumn.setObjectName(_fromUtf8("cMColumn"))
        self.gridLayout_2.addWidget(self.cMColumn, 2, 3, 1, 1)
        self.cXColumn = QtGui.QSpinBox(self.groupBox)
        self.cXColumn.setMinimum(0)
        self.cXColumn.setMaximum(100)
        self.cXColumn.setProperty("value", 1)
        self.cXColumn.setObjectName(_fromUtf8("cXColumn"))
        self.gridLayout_2.addWidget(self.cXColumn, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.cMCheck = QtGui.QCheckBox(self.groupBox)
        self.cMCheck.setEnabled(True)
        self.cMCheck.setCheckable(True)
        self.cMCheck.setChecked(False)
        self.cMCheck.setTristate(False)
        self.cMCheck.setObjectName(_fromUtf8("cMCheck"))
        self.gridLayout_2.addWidget(self.cMCheck, 0, 3, 1, 1)
        self.cCutForward = QtGui.QCheckBox(self.groupBox)
        self.cCutForward.setObjectName(_fromUtf8("cCutForward"))
        self.gridLayout_2.addWidget(self.cCutForward, 2, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.cLoad = QtGui.QPushButton(self.groupBox)
        self.cLoad.setEnabled(False)
        self.cLoad.setObjectName(_fromUtf8("cLoad"))
        self.verticalLayout_7.addWidget(self.cLoad)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.line = QtGui.QFrame(self.tab_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_2.addWidget(self.label_33)
        self.sPath = QtGui.QLineEdit(self.groupBox_2)
        self.sPath.setText(_fromUtf8(""))
        self.sPath.setObjectName(_fromUtf8("sPath"))
        self.horizontalLayout_2.addWidget(self.sPath)
        self.sFile = QtGui.QPushButton(self.groupBox_2)
        self.sFile.setObjectName(_fromUtf8("sFile"))
        self.horizontalLayout_2.addWidget(self.sFile)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.sYColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sYColumn.setMinimum(0)
        self.sYColumn.setMaximum(50)
        self.sYColumn.setProperty("value", 3)
        self.sYColumn.setObjectName(_fromUtf8("sYColumn"))
        self.gridLayout_4.addWidget(self.sYColumn, 1, 1, 1, 1)
        self.sMColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sMColumn.setMinimum(0)
        self.sMColumn.setMaximum(50)
        self.sMColumn.setProperty("value", 1)
        self.sMColumn.setObjectName(_fromUtf8("sMColumn"))
        self.gridLayout_4.addWidget(self.sMColumn, 1, 3, 1, 1)
        self.sXColumn = QtGui.QSpinBox(self.groupBox_2)
        self.sXColumn.setMinimum(0)
        self.sXColumn.setMaximum(50)
        self.sXColumn.setProperty("value", 1)
        self.sXColumn.setObjectName(_fromUtf8("sXColumn"))
        self.gridLayout_4.addWidget(self.sXColumn, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.sMCheck = QtGui.QCheckBox(self.groupBox_2)
        self.sMCheck.setEnabled(True)
        self.sMCheck.setCheckable(True)
        self.sMCheck.setChecked(False)
        self.sMCheck.setTristate(False)
        self.sMCheck.setObjectName(_fromUtf8("sMCheck"))
        self.gridLayout_4.addWidget(self.sMCheck, 0, 3, 1, 1)
        self.sCutForward = QtGui.QCheckBox(self.groupBox_2)
        self.sCutForward.setObjectName(_fromUtf8("sCutForward"))
        self.gridLayout_4.addWidget(self.sCutForward, 1, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.sLoad = QtGui.QPushButton(self.groupBox_2)
        self.sLoad.setEnabled(False)
        self.sLoad.setObjectName(_fromUtf8("sLoad"))
        self.verticalLayout_8.addWidget(self.sLoad)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.line_2 = QtGui.QFrame(self.tab_1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_6.addWidget(self.line_2)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 2, 1, 1)
        self.cPolyP = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyP.setDecimals(3)
        self.cPolyP.setMinimum(0.001)
        self.cPolyP.setMaximum(999.0)
        self.cPolyP.setSingleStep(0.01)
        self.cPolyP.setProperty("value", 0.9)
        self.cPolyP.setObjectName(_fromUtf8("cPolyP"))
        self.gridLayout_6.addWidget(self.cPolyP, 1, 1, 1, 1)
        self.cPolyM = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyM.setDecimals(0)
        self.cPolyM.setProperty("value", 6.0)
        self.cPolyM.setObjectName(_fromUtf8("cPolyM"))
        self.gridLayout_6.addWidget(self.cPolyM, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 1, 1, 1)
        self.cPolyN = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.cPolyN.setDecimals(0)
        self.cPolyN.setMinimum(1.0)
        self.cPolyN.setMaximum(999999999.0)
        self.cPolyN.setSingleStep(1.0)
        self.cPolyN.setProperty("value", 80.0)
        self.cPolyN.setObjectName(_fromUtf8("cPolyN"))
        self.gridLayout_6.addWidget(self.cPolyN, 1, 0, 1, 1)
        self.cPolyOk = QtGui.QPushButton(self.groupBox_5)
        self.cPolyOk.setObjectName(_fromUtf8("cPolyOk"))
        self.gridLayout_6.addWidget(self.cPolyOk, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.cAverageStep = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.cAverageStep.setDecimals(6)
        self.cAverageStep.setMinimum(1e-06)
        self.cAverageStep.setMaximum(999999999.0)
        self.cAverageStep.setSingleStep(0.01)
        self.cAverageStep.setProperty("value", 0.01)
        self.cAverageStep.setObjectName(_fromUtf8("cAverageStep"))
        self.gridLayout.addWidget(self.cAverageStep, 1, 0, 1, 1)
        self.cAverageOk = QtGui.QPushButton(self.groupBox_7)
        self.cAverageOk.setObjectName(_fromUtf8("cAverageOk"))
        self.gridLayout.addWidget(self.cAverageOk, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.cB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineStep.setDecimals(3)
        self.cB_splineStep.setMinimum(0.001)
        self.cB_splineStep.setMaximum(99999.0)
        self.cB_splineStep.setSingleStep(0.5)
        self.cB_splineStep.setProperty("value", 1.0)
        self.cB_splineStep.setObjectName(_fromUtf8("cB_splineStep"))
        self.gridLayout_7.addWidget(self.cB_splineStep, 1, 0, 1, 1)
        self.cB_splineS = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineS.setDecimals(4)
        self.cB_splineS.setMinimum(0.0)
        self.cB_splineS.setMaximum(999999999.0)
        self.cB_splineS.setSingleStep(0.05)
        self.cB_splineS.setProperty("value", 1500000.0)
        self.cB_splineS.setObjectName(_fromUtf8("cB_splineS"))
        self.gridLayout_7.addWidget(self.cB_splineS, 1, 1, 1, 1)
        self.cB_splineK = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.cB_splineK.setDecimals(0)
        self.cB_splineK.setMaximum(5.0)
        self.cB_splineK.setProperty("value", 4.0)
        self.cB_splineK.setObjectName(_fromUtf8("cB_splineK"))
        self.gridLayout_7.addWidget(self.cB_splineK, 1, 2, 1, 1)
        self.cB_splineOk = QtGui.QPushButton(self.groupBox_8)
        self.cB_splineOk.setObjectName(_fromUtf8("cB_splineOk"))
        self.gridLayout_7.addWidget(self.cB_splineOk, 1, 3, 1, 1)
        self.cAutoB_splineS = QtGui.QCheckBox(self.groupBox_8)
        self.cAutoB_splineS.setObjectName(_fromUtf8("cAutoB_splineS"))
        self.gridLayout_7.addWidget(self.cAutoB_splineS, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setEnabled(False)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.cMedFiltS = QtGui.QSpinBox(self.groupBox_9)
        self.cMedFiltS.setMinimum(1)
        self.cMedFiltS.setSingleStep(2)
        self.cMedFiltS.setProperty("value", 3)
        self.cMedFiltS.setObjectName(_fromUtf8("cMedFiltS"))
        self.horizontalLayout_12.addWidget(self.cMedFiltS)
        self.cMedFilt = QtGui.QPushButton(self.groupBox_9)
        self.cMedFilt.setObjectName(_fromUtf8("cMedFilt"))
        self.horizontalLayout_12.addWidget(self.cMedFilt)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_21 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_19 = QtGui.QLabel(self.groupBox_21)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_22.addWidget(self.label_19)
        self.cXFilt = QtGui.QLineEdit(self.groupBox_21)
        self.cXFilt.setEnabled(True)
        self.cXFilt.setMaxLength(100)
        self.cXFilt.setObjectName(_fromUtf8("cXFilt"))
        self.horizontalLayout_22.addWidget(self.cXFilt)
        self.label_27 = QtGui.QLabel(self.groupBox_21)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_22.addWidget(self.label_27)
        self.cYFilt = QtGui.QLineEdit(self.groupBox_21)
        self.cYFilt.setEnabled(True)
        self.cYFilt.setMaxLength(100)
        self.cYFilt.setObjectName(_fromUtf8("cYFilt"))
        self.horizontalLayout_22.addWidget(self.cYFilt)
        self.cFiltOk = QtGui.QPushButton(self.groupBox_21)
        self.cFiltOk.setObjectName(_fromUtf8("cFiltOk"))
        self.horizontalLayout_22.addWidget(self.cFiltOk)
        self.verticalLayout_2.addWidget(self.groupBox_21)
        self.cSave = QtGui.QPushButton(self.tab_2)
        self.cSave.setObjectName(_fromUtf8("cSave"))
        self.verticalLayout_2.addWidget(self.cSave)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_11)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 0, 2, 1, 1)
        self.sPolyN = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyN.setDecimals(0)
        self.sPolyN.setMinimum(1.0)
        self.sPolyN.setMaximum(999999999.0)
        self.sPolyN.setSingleStep(1.0)
        self.sPolyN.setProperty("value", 80.0)
        self.sPolyN.setObjectName(_fromUtf8("sPolyN"))
        self.gridLayout_10.addWidget(self.sPolyN, 1, 0, 1, 1)
        self.sPolyP = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyP.setDecimals(3)
        self.sPolyP.setMinimum(0.001)
        self.sPolyP.setMaximum(999.0)
        self.sPolyP.setSingleStep(0.01)
        self.sPolyP.setProperty("value", 0.9)
        self.sPolyP.setObjectName(_fromUtf8("sPolyP"))
        self.gridLayout_10.addWidget(self.sPolyP, 1, 1, 1, 1)
        self.sPolyM = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.sPolyM.setDecimals(0)
        self.sPolyM.setProperty("value", 6.0)
        self.sPolyM.setObjectName(_fromUtf8("sPolyM"))
        self.gridLayout_10.addWidget(self.sPolyM, 1, 2, 1, 1)
        self.sPolyOk = QtGui.QPushButton(self.groupBox_11)
        self.sPolyOk.setObjectName(_fromUtf8("sPolyOk"))
        self.gridLayout_10.addWidget(self.sPolyOk, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.sAverageStep = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.sAverageStep.setDecimals(6)
        self.sAverageStep.setMinimum(1e-06)
        self.sAverageStep.setMaximum(999999999.0)
        self.sAverageStep.setSingleStep(0.01)
        self.sAverageStep.setProperty("value", 0.01)
        self.sAverageStep.setObjectName(_fromUtf8("sAverageStep"))
        self.horizontalLayout_19.addWidget(self.sAverageStep)
        self.label_26 = QtGui.QLabel(self.groupBox_15)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_19.addWidget(self.label_26)
        self.sAverageOk = QtGui.QPushButton(self.groupBox_15)
        self.sAverageOk.setObjectName(_fromUtf8("sAverageOk"))
        self.horizontalLayout_19.addWidget(self.sAverageOk)
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_21 = QtGui.QLabel(self.groupBox_10)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_10)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_10)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.sB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineStep.setDecimals(3)
        self.sB_splineStep.setMinimum(0.001)
        self.sB_splineStep.setMaximum(999999999.0)
        self.sB_splineStep.setSingleStep(0.5)
        self.sB_splineStep.setProperty("value", 1.0)
        self.sB_splineStep.setObjectName(_fromUtf8("sB_splineStep"))
        self.gridLayout_3.addWidget(self.sB_splineStep, 1, 0, 1, 1)
        self.sB_splineS = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineS.setDecimals(4)
        self.sB_splineS.setMinimum(0.0)
        self.sB_splineS.setMaximum(999999999.0)
        self.sB_splineS.setSingleStep(0.05)
        self.sB_splineS.setProperty("value", 1500000.0)
        self.sB_splineS.setObjectName(_fromUtf8("sB_splineS"))
        self.gridLayout_3.addWidget(self.sB_splineS, 1, 1, 1, 1)
        self.sB_splineK = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.sB_splineK.setDecimals(0)
        self.sB_splineK.setMaximum(5.0)
        self.sB_splineK.setProperty("value", 4.0)
        self.sB_splineK.setObjectName(_fromUtf8("sB_splineK"))
        self.gridLayout_3.addWidget(self.sB_splineK, 1, 2, 1, 1)
        self.sB_splineOk = QtGui.QPushButton(self.groupBox_10)
        self.sB_splineOk.setObjectName(_fromUtf8("sB_splineOk"))
        self.gridLayout_3.addWidget(self.sB_splineOk, 1, 3, 1, 1)
        self.sAutoB_splineS = QtGui.QCheckBox(self.groupBox_10)
        self.sAutoB_splineS.setObjectName(_fromUtf8("sAutoB_splineS"))
        self.gridLayout_3.addWidget(self.sAutoB_splineS, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setEnabled(False)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 0, 1, 1)
        self.sMedFiltS = QtGui.QSpinBox(self.groupBox_12)
        self.sMedFiltS.setMinimum(1)
        self.sMedFiltS.setSingleStep(2)
        self.sMedFiltS.setProperty("value", 3)
        self.sMedFiltS.setObjectName(_fromUtf8("sMedFiltS"))
        self.gridLayout_9.addWidget(self.sMedFiltS, 0, 1, 1, 1)
        self.sMedFilt = QtGui.QPushButton(self.groupBox_12)
        self.sMedFilt.setObjectName(_fromUtf8("sMedFilt"))
        self.gridLayout_9.addWidget(self.sMedFilt, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.groupBox_22 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.groupBox_22)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.sXFilt = QtGui.QLineEdit(self.groupBox_22)
        self.sXFilt.setEnabled(True)
        self.sXFilt.setObjectName(_fromUtf8("sXFilt"))
        self.horizontalLayout_23.addWidget(self.sXFilt)
        self.label_29 = QtGui.QLabel(self.groupBox_22)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_23.addWidget(self.label_29)
        self.sYFilt = QtGui.QLineEdit(self.groupBox_22)
        self.sYFilt.setEnabled(True)
        self.sYFilt.setObjectName(_fromUtf8("sYFilt"))
        self.horizontalLayout_23.addWidget(self.sYFilt)
        self.sFiltOk = QtGui.QPushButton(self.groupBox_22)
        self.sFiltOk.setObjectName(_fromUtf8("sFiltOk"))
        self.horizontalLayout_23.addWidget(self.sFiltOk)
        self.verticalLayout_3.addWidget(self.groupBox_22)
        self.sSave = QtGui.QPushButton(self.tab_3)
        self.sSave.setObjectName(_fromUtf8("sSave"))
        self.verticalLayout_3.addWidget(self.sSave)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.rButton = QtGui.QPushButton(self.tab_4)
        self.rButton.setObjectName(_fromUtf8("rButton"))
        self.horizontalLayout_11.addWidget(self.rButton)
        self.rEvalType = QtGui.QComboBox(self.tab_4)
        self.rEvalType.setObjectName(_fromUtf8("rEvalType"))
        self.rEvalType.addItem(_fromUtf8(""))
        self.rEvalType.addItem(_fromUtf8(""))
        self.rEvalType.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.rEvalType)
        self.rYInPercents = QtGui.QCheckBox(self.tab_4)
        self.rYInPercents.setObjectName(_fromUtf8("rYInPercents"))
        self.horizontalLayout_11.addWidget(self.rYInPercents)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_19 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_50 = QtGui.QLabel(self.groupBox_19)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_19)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_19)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 2, 1, 1)
        self.rB_splineStep = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineStep.setDecimals(4)
        self.rB_splineStep.setMinimum(0.001)
        self.rB_splineStep.setMaximum(99999.0)
        self.rB_splineStep.setSingleStep(0.5)
        self.rB_splineStep.setProperty("value", 1.0)
        self.rB_splineStep.setObjectName(_fromUtf8("rB_splineStep"))
        self.gridLayout_8.addWidget(self.rB_splineStep, 1, 0, 1, 1)
        self.rB_splineS = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineS.setDecimals(4)
        self.rB_splineS.setMinimum(0.0)
        self.rB_splineS.setMaximum(999999999.0)
        self.rB_splineS.setSingleStep(0.01)
        self.rB_splineS.setProperty("value", 10.0)
        self.rB_splineS.setObjectName(_fromUtf8("rB_splineS"))
        self.gridLayout_8.addWidget(self.rB_splineS, 1, 1, 1, 1)
        self.rB_splineK = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.rB_splineK.setDecimals(0)
        self.rB_splineK.setMaximum(5.0)
        self.rB_splineK.setProperty("value", 4.0)
        self.rB_splineK.setObjectName(_fromUtf8("rB_splineK"))
        self.gridLayout_8.addWidget(self.rB_splineK, 1, 2, 1, 1)
        self.rAutoB_splineS = QtGui.QCheckBox(self.groupBox_19)
        self.rAutoB_splineS.setObjectName(_fromUtf8("rAutoB_splineS"))
        self.gridLayout_8.addWidget(self.rAutoB_splineS, 2, 1, 1, 1)
        self.rB_splineOk = QtGui.QPushButton(self.groupBox_19)
        self.rB_splineOk.setObjectName(_fromUtf8("rB_splineOk"))
        self.gridLayout_8.addWidget(self.rB_splineOk, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_19)
        self.groupBox_20 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_20.setEnabled(False)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_30 = QtGui.QLabel(self.groupBox_20)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_14.addWidget(self.label_30)
        self.rMedFiltS = QtGui.QSpinBox(self.groupBox_20)
        self.rMedFiltS.setMinimum(1)
        self.rMedFiltS.setSingleStep(2)
        self.rMedFiltS.setProperty("value", 3)
        self.rMedFiltS.setObjectName(_fromUtf8("rMedFiltS"))
        self.horizontalLayout_14.addWidget(self.rMedFiltS)
        self.rMedFilt = QtGui.QPushButton(self.groupBox_20)
        self.rMedFilt.setObjectName(_fromUtf8("rMedFilt"))
        self.horizontalLayout_14.addWidget(self.rMedFilt)
        self.verticalLayout_5.addWidget(self.groupBox_20)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rSave = QtGui.QPushButton(self.tab_4)
        self.rSave.setObjectName(_fromUtf8("rSave"))
        self.gridLayout_5.addWidget(self.rSave, 2, 1, 1, 1)
        self.rPlot = QtGui.QPushButton(self.tab_4)
        self.rPlot.setObjectName(_fromUtf8("rPlot"))
        self.gridLayout_5.addWidget(self.rPlot, 2, 0, 1, 1)
        self.rSaveSuffix = QtGui.QLineEdit(self.tab_4)
        self.rSaveSuffix.setInputMask(_fromUtf8(""))
        self.rSaveSuffix.setMaxLength(32767)
        self.rSaveSuffix.setObjectName(_fromUtf8("rSaveSuffix"))
        self.gridLayout_5.addWidget(self.rSaveSuffix, 1, 1, 1, 1)
        self.rSavePrefix = QtGui.QLineEdit(self.tab_4)
        self.rSavePrefix.setObjectName(_fromUtf8("rSavePrefix"))
        self.gridLayout_5.addWidget(self.rSavePrefix, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.toggleTabs = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleTabs.sizePolicy().hasHeightForWidth())
        self.toggleTabs.setSizePolicy(sizePolicy)
        self.toggleTabs.setCheckable(True)
        self.toggleTabs.setChecked(True)
        self.toggleTabs.setFlat(True)
        self.toggleTabs.setObjectName(_fromUtf8("toggleTabs"))
        self.verticalLayout.addWidget(self.toggleTabs)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(1)
        self.horizontalLayout_21.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.mplactionCut_by_line = QtGui.QCheckBox(self.frame)
        self.mplactionCut_by_line.setCheckable(True)
        self.mplactionCut_by_line.setObjectName(_fromUtf8("mplactionCut_by_line"))
        self.horizontalLayout_21.addWidget(self.mplactionCut_by_line)
        self.mplactionCut_by_rect = QtGui.QCheckBox(self.frame)
        self.mplactionCut_by_rect.setCheckable(True)
        self.mplactionCut_by_rect.setObjectName(_fromUtf8("mplactionCut_by_rect"))
        self.horizontalLayout_21.addWidget(self.mplactionCut_by_rect)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_21.addWidget(self.label_13)
        self.mplhorizontalSlider = QtGui.QSlider(self.frame)
        self.mplhorizontalSlider.setProperty("value", 3)
        self.mplhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mplhorizontalSlider.setObjectName(_fromUtf8("mplhorizontalSlider"))
        self.horizontalLayout_21.addWidget(self.mplhorizontalSlider)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        self.xLogScale = QtGui.QCheckBox(self.frame)
        self.xLogScale.setObjectName(_fromUtf8("xLogScale"))
        self.horizontalLayout_21.addWidget(self.xLogScale)
        self.yLogScale = QtGui.QCheckBox(self.frame)
        self.yLogScale.setObjectName(_fromUtf8("yLogScale"))
        self.horizontalLayout_21.addWidget(self.yLogScale)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.mpl = MplWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.verticalLayout_4.addWidget(self.mpl)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_20.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1006, 28))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_6 = QtGui.QMenu(self.menu_2)
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        self.menu_Scale = QtGui.QMenu(self.menu_2)
        self.menu_Scale.setObjectName(_fromUtf8("menu_Scale"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menuBar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_Hist = QtGui.QMenu(self.menuBar)
        self.menu_Hist.setObjectName(_fromUtf8("menu_Hist"))
        self.projects = QtGui.QMenu(self.menuBar)
        self.projects.setObjectName(_fromUtf8("projects"))
        self.addToProjMenu = QtGui.QMenu(self.projects)
        self.addToProjMenu.setObjectName(_fromUtf8("addToProjMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar_1 = QtGui.QToolBar(MainWindow)
        self.toolBar_1.setFloatable(True)
        self.toolBar_1.setObjectName(_fromUtf8("toolBar_1"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_1)
        self.saveSettings = QtGui.QAction(MainWindow)
        self.saveSettings.setObjectName(_fromUtf8("saveSettings"))
        self.loadSettings = QtGui.QAction(MainWindow)
        self.loadSettings.setObjectName(_fromUtf8("loadSettings"))
        self.recalcIntens = QtGui.QAction(MainWindow)
        self.recalcIntens.setObjectName(_fromUtf8("recalcIntens"))
        self.Discrete = QtGui.QAction(MainWindow)
        self.Discrete.setCheckable(True)
        self.Discrete.setObjectName(_fromUtf8("Discrete"))
        self.Close = QtGui.QAction(MainWindow)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.actionY_X = QtGui.QAction(MainWindow)
        self.actionY_X.setCheckable(True)
        self.actionY_X.setObjectName(_fromUtf8("actionY_X"))
        self.actionX_Log10 = QtGui.QAction(MainWindow)
        self.actionX_Log10.setCheckable(True)
        self.actionX_Log10.setObjectName(_fromUtf8("actionX_Log10"))
        self.actionY_Log10 = QtGui.QAction(MainWindow)
        self.actionY_Log10.setCheckable(True)
        self.actionY_Log10.setObjectName(_fromUtf8("actionY_Log10"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setEnabled(False)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.processAll = QtGui.QAction(MainWindow)
        self.processAll.setCheckable(True)
        self.processAll.setChecked(True)
        self.processAll.setObjectName(_fromUtf8("processAll"))
        self.processView = QtGui.QAction(MainWindow)
        self.processView.setCheckable(True)
        self.processView.setObjectName(_fromUtf8("processView"))
        self.Undo = QtGui.QAction(MainWindow)
        self.Undo.setMenuRole(QtGui.QAction.ApplicationSpecificRole)
        self.Undo.setObjectName(_fromUtf8("Undo"))
        self.Reset = QtGui.QAction(MainWindow)
        self.Reset.setObjectName(_fromUtf8("Reset"))
        self.norm_Max = QtGui.QAction(MainWindow)
        self.norm_Max.setObjectName(_fromUtf8("norm_Max"))
        self.norm_Point = QtGui.QAction(MainWindow)
        self.norm_Point.setObjectName(_fromUtf8("norm_Point"))
        self.settings = QtGui.QAction(MainWindow)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.createProj = QtGui.QAction(MainWindow)
        self.createProj.setObjectName(_fromUtf8("createProj"))
        self.norm_FirstPoint = QtGui.QAction(MainWindow)
        self.norm_FirstPoint.setObjectName(_fromUtf8("norm_FirstPoint"))
        self.autoScale = QtGui.QAction(MainWindow)
        self.autoScale.setCheckable(True)
        self.autoScale.setChecked(True)
        self.autoScale.setObjectName(_fromUtf8("autoScale"))
        self.tmpShow = QtGui.QAction(MainWindow)
        self.tmpShow.setCheckable(True)
        self.tmpShow.setChecked(False)
        self.tmpShow.setObjectName(_fromUtf8("tmpShow"))
        self.menu.addAction(self.settings)
        self.menu_6.addAction(self.norm_Max)
        self.menu_6.addAction(self.norm_Point)
        self.menu_6.addAction(self.norm_FirstPoint)
        self.menu_Scale.addAction(self.actionY_Log10)
        self.menu_Scale.addAction(self.actionX_Log10)
        self.menu_Scale.addAction(self.actionY_X)
        self.menu_2.addAction(self.recalcIntens)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_Scale.menuAction())
        self.menu_2.addAction(self.autoScale)
        self.menu_2.addAction(self.tmpShow)
        self.menu_2.addAction(self.menu_6.menuAction())
        self.menu_3.addAction(self.Discrete)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.processView)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.Close)
        self.menu_Hist.addAction(self.Undo)
        self.menu_Hist.addAction(self.Reset)
        self.addToProjMenu.addSeparator()
        self.projects.addAction(self.createProj)
        self.projects.addSeparator()
        self.projects.addAction(self.addToProjMenu.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_Hist.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.projects.menuAction())
        self.toolBar_1.addAction(self.autoScale)
        self.toolBar_1.addAction(self.tmpShow)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cPath, self.cFile)
        MainWindow.setTabOrder(self.cFile, self.cXColumn)
        MainWindow.setTabOrder(self.cXColumn, self.cYColumn)
        MainWindow.setTabOrder(self.cYColumn, self.cMColumn)
        MainWindow.setTabOrder(self.cMColumn, self.cMCheck)
        MainWindow.setTabOrder(self.cMCheck, self.cCutForward)
        MainWindow.setTabOrder(self.cCutForward, self.cLoad)
        MainWindow.setTabOrder(self.cLoad, self.sPath)
        MainWindow.setTabOrder(self.sPath, self.sFile)
        MainWindow.setTabOrder(self.sFile, self.sXColumn)
        MainWindow.setTabOrder(self.sXColumn, self.sYColumn)
        MainWindow.setTabOrder(self.sYColumn, self.sMColumn)
        MainWindow.setTabOrder(self.sMColumn, self.sMCheck)
        MainWindow.setTabOrder(self.sMCheck, self.sCutForward)
        MainWindow.setTabOrder(self.sCutForward, self.sLoad)
        MainWindow.setTabOrder(self.sLoad, self.cPolyN)
        MainWindow.setTabOrder(self.cPolyN, self.cPolyP)
        MainWindow.setTabOrder(self.cPolyP, self.cPolyM)
        MainWindow.setTabOrder(self.cPolyM, self.cPolyOk)
        MainWindow.setTabOrder(self.cPolyOk, self.cAverageStep)
        MainWindow.setTabOrder(self.cAverageStep, self.cAverageOk)
        MainWindow.setTabOrder(self.cAverageOk, self.cB_splineStep)
        MainWindow.setTabOrder(self.cB_splineStep, self.cB_splineS)
        MainWindow.setTabOrder(self.cB_splineS, self.cB_splineK)
        MainWindow.setTabOrder(self.cB_splineK, self.cAutoB_splineS)
        MainWindow.setTabOrder(self.cAutoB_splineS, self.cB_splineOk)
        MainWindow.setTabOrder(self.cB_splineOk, self.cMedFiltS)
        MainWindow.setTabOrder(self.cMedFiltS, self.cMedFilt)
        MainWindow.setTabOrder(self.cMedFilt, self.cXFilt)
        MainWindow.setTabOrder(self.cXFilt, self.cYFilt)
        MainWindow.setTabOrder(self.cYFilt, self.cFiltOk)
        MainWindow.setTabOrder(self.cFiltOk, self.cSave)
        MainWindow.setTabOrder(self.cSave, self.sPolyN)
        MainWindow.setTabOrder(self.sPolyN, self.sPolyP)
        MainWindow.setTabOrder(self.sPolyP, self.sPolyM)
        MainWindow.setTabOrder(self.sPolyM, self.sPolyOk)
        MainWindow.setTabOrder(self.sPolyOk, self.sAverageStep)
        MainWindow.setTabOrder(self.sAverageStep, self.sAverageOk)
        MainWindow.setTabOrder(self.sAverageOk, self.sB_splineStep)
        MainWindow.setTabOrder(self.sB_splineStep, self.sB_splineS)
        MainWindow.setTabOrder(self.sB_splineS, self.sB_splineK)
        MainWindow.setTabOrder(self.sB_splineK, self.sAutoB_splineS)
        MainWindow.setTabOrder(self.sAutoB_splineS, self.sB_splineOk)
        MainWindow.setTabOrder(self.sB_splineOk, self.sMedFiltS)
        MainWindow.setTabOrder(self.sMedFiltS, self.sMedFilt)
        MainWindow.setTabOrder(self.sMedFilt, self.sXFilt)
        MainWindow.setTabOrder(self.sXFilt, self.sYFilt)
        MainWindow.setTabOrder(self.sYFilt, self.sFiltOk)
        MainWindow.setTabOrder(self.sFiltOk, self.sSave)
        MainWindow.setTabOrder(self.sSave, self.rButton)
        MainWindow.setTabOrder(self.rButton, self.rEvalType)
        MainWindow.setTabOrder(self.rEvalType, self.rB_splineStep)
        MainWindow.setTabOrder(self.rB_splineStep, self.rB_splineS)
        MainWindow.setTabOrder(self.rB_splineS, self.rB_splineK)
        MainWindow.setTabOrder(self.rB_splineK, self.rAutoB_splineS)
        MainWindow.setTabOrder(self.rAutoB_splineS, self.rB_splineOk)
        MainWindow.setTabOrder(self.rB_splineOk, self.rMedFiltS)
        MainWindow.setTabOrder(self.rMedFiltS, self.rMedFilt)
        MainWindow.setTabOrder(self.rMedFilt, self.rPlot)
        MainWindow.setTabOrder(self.rPlot, self.rSave)
        MainWindow.setTabOrder(self.rSave, self.mplactionCut_by_line)
        MainWindow.setTabOrder(self.mplactionCut_by_line, self.mplactionCut_by_rect)
        MainWindow.setTabOrder(self.mplactionCut_by_rect, self.mplhorizontalSlider)
        MainWindow.setTabOrder(self.mplhorizontalSlider, self.xLogScale)
        MainWindow.setTabOrder(self.xLogScale, self.yLogScale)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QTR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.cPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.cFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cMCheck.setText(QtGui.QApplication.translate("MainWindow", "Коеф. підс.", None, QtGui.QApplication.UnicodeUTF8))
        self.cCutForward.setText(QtGui.QApplication.translate("MainWindow", "Вперед", None, QtGui.QApplication.UnicodeUTF8))
        self.cLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.sPath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "./", None, QtGui.QApplication.UnicodeUTF8))
        self.sFile.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sMCheck.setText(QtGui.QApplication.translate("MainWindow", "Коеф. підс.", None, QtGui.QApplication.UnicodeUTF8))
        self.sCutForward.setText(QtGui.QApplication.translate("MainWindow", "Вперед", None, QtGui.QApplication.UnicodeUTF8))
        self.sLoad.setText(QtGui.QApplication.translate("MainWindow", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Вхідні дані", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyP.setToolTip(QtGui.QApplication.translate("MainWindow", "Відсоток від максимального відхилення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyN.setToolTip(QtGui.QApplication.translate("MainWindow", "Розмір порцій, для яких буде проводитись обробка", None, QtGui.QApplication.UnicodeUTF8))
        self.cPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.cAverageStep.setToolTip(QtGui.QApplication.translate("MainWindow", "Розмір порцій, для яких буде проводитись усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.cAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Згладжув.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерп.", None, QtGui.QApplication.UnicodeUTF8))
        self.cAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра:", None, QtGui.QApplication.UnicodeUTF8))
        self.cMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_21.setTitle(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cFiltOk.setText(QtGui.QApplication.translate("MainWindow", "Застосувати", None, QtGui.QApplication.UnicodeUTF8))
        self.cSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.sPolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.sAverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Згладжув.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.sB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерпол.", None, QtGui.QApplication.UnicodeUTF8))
        self.sAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра:", None, QtGui.QApplication.UnicodeUTF8))
        self.sMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_22.setTitle(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sFiltOk.setText(QtGui.QApplication.translate("MainWindow", "Застосувати", None, QtGui.QApplication.UnicodeUTF8))
        self.sSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.rButton.setText(QtGui.QApplication.translate("MainWindow", "Обчислити", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(0, QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(1, QtGui.QApplication.translate("MainWindow", "nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.rEvalType.setItemText(2, QtGui.QApplication.translate("MainWindow", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.rYInPercents.setText(QtGui.QApplication.translate("MainWindow", "Y, %", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_19.setTitle(QtGui.QApplication.translate("MainWindow", "B-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Коеф. згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.rAutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.rB_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерполювати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_20.setTitle(QtGui.QApplication.translate("MainWindow", "Медіанний фільтр", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Розмір ядра", None, QtGui.QApplication.UnicodeUTF8))
        self.rMedFilt.setText(QtGui.QApplication.translate("MainWindow", "Фільтрувати", None, QtGui.QApplication.UnicodeUTF8))
        self.rSave.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.rPlot.setText(QtGui.QApplication.translate("MainWindow", "Побудувати", None, QtGui.QApplication.UnicodeUTF8))
        self.rSaveSuffix.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "суфікс", None, QtGui.QApplication.UnicodeUTF8))
        self.rSavePrefix.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "префікс", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Результат", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleTabs.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionCut_by_line.setText(QtGui.QApplication.translate("MainWindow", "Лінія", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionCut_by_rect.setText(QtGui.QApplication.translate("MainWindow", "Прямокутник", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Розмір точок: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Log10:", None, QtGui.QApplication.UnicodeUTF8))
        self.xLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.yLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Налаштування", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Обробка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_6.setTitle(QtGui.QApplication.translate("MainWindow", "Нормувати", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Scale.setTitle(QtGui.QApplication.translate("MainWindow", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Режим", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Hist.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.projects.setTitle(QtGui.QApplication.translate("MainWindow", "Проект", None, QtGui.QApplication.UnicodeUTF8))
        self.addToProjMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Додати до існуючого", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_1.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettings.setText(QtGui.QApplication.translate("MainWindow", "зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettings.setText(QtGui.QApplication.translate("MainWindow", "завантажити", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcIntens.setText(QtGui.QApplication.translate("MainWindow", "Посадити на інтенсивність", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcIntens.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.Discrete.setText(QtGui.QApplication.translate("MainWindow", "Дискретний", None, QtGui.QApplication.UnicodeUTF8))
        self.Discrete.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("MainWindow", "Вийти", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q, Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_X.setText(QtGui.QApplication.translate("MainWindow", "y -> Y/X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_Log10.setText(QtGui.QApplication.translate("MainWindow", "x -> Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_Log10.setText(QtGui.QApplication.translate("MainWindow", "y -> Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.action_5.setText(QtGui.QApplication.translate("MainWindow", "Межі обробки:", None, QtGui.QApplication.UnicodeUTF8))
        self.processAll.setText(QtGui.QApplication.translate("MainWindow", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.processView.setText(QtGui.QApplication.translate("MainWindow", "Видимий діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.Undo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.Undo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_Max.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на максимум", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_Point.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на вказану точку", None, QtGui.QApplication.UnicodeUTF8))
        self.settings.setText(QtGui.QApplication.translate("MainWindow", "Параметри", None, QtGui.QApplication.UnicodeUTF8))
        self.createProj.setText(QtGui.QApplication.translate("MainWindow", "Створити", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_FirstPoint.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на першу точку", None, QtGui.QApplication.UnicodeUTF8))
        self.autoScale.setText(QtGui.QApplication.translate("MainWindow", "Автомасштабування", None, QtGui.QApplication.UnicodeUTF8))
        self.tmpShow.setText(QtGui.QApplication.translate("MainWindow", "Проміжні побудови", None, QtGui.QApplication.UnicodeUTF8))

from ui.mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

