# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kronosua/work/QTR/ui/form.ui'
#
# Created: Sun Feb 24 03:10:39 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1005, 695)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(448, 695))
        MainWindow.setBaseSize(QtCore.QSize(900, 620))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mpl = MplWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.verticalLayout_4.addWidget(self.mpl)
        self.verticalLayout.addWidget(self.frame)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_Average = QtGui.QWidget()
        self.page_Average.setObjectName(_fromUtf8("page_Average"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_Average)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_15 = QtGui.QGroupBox(self.page_Average)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_26 = QtGui.QLabel(self.groupBox_15)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_4.addWidget(self.label_26)
        self.AverageStep = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.AverageStep.setDecimals(6)
        self.AverageStep.setMinimum(1e-06)
        self.AverageStep.setMaximum(999999999.0)
        self.AverageStep.setSingleStep(0.01)
        self.AverageStep.setProperty("value", 0.01)
        self.AverageStep.setObjectName(_fromUtf8("AverageStep"))
        self.horizontalLayout_4.addWidget(self.AverageStep)
        self.AverageOk = QtGui.QPushButton(self.groupBox_15)
        self.AverageOk.setObjectName(_fromUtf8("AverageOk"))
        self.horizontalLayout_4.addWidget(self.AverageOk)
        self.horizontalLayout_5.addWidget(self.groupBox_15)
        self.stackedWidget.addWidget(self.page_Average)
        self.page_PolyCut = QtGui.QWidget()
        self.page_PolyCut.setObjectName(_fromUtf8("page_PolyCut"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_PolyCut)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_11 = QtGui.QGroupBox(self.page_PolyCut)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_11)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 0, 2, 1, 1)
        self.PolyN = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.PolyN.setDecimals(0)
        self.PolyN.setMinimum(1.0)
        self.PolyN.setMaximum(999999999.0)
        self.PolyN.setSingleStep(1.0)
        self.PolyN.setProperty("value", 80.0)
        self.PolyN.setObjectName(_fromUtf8("PolyN"))
        self.gridLayout_10.addWidget(self.PolyN, 1, 0, 1, 1)
        self.PolyP = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.PolyP.setDecimals(3)
        self.PolyP.setMinimum(0.001)
        self.PolyP.setMaximum(999.0)
        self.PolyP.setSingleStep(0.01)
        self.PolyP.setProperty("value", 0.9)
        self.PolyP.setObjectName(_fromUtf8("PolyP"))
        self.gridLayout_10.addWidget(self.PolyP, 1, 1, 1, 1)
        self.PolyM = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.PolyM.setDecimals(0)
        self.PolyM.setProperty("value", 6.0)
        self.PolyM.setObjectName(_fromUtf8("PolyM"))
        self.gridLayout_10.addWidget(self.PolyM, 1, 2, 1, 1)
        self.PolyOk = QtGui.QPushButton(self.groupBox_11)
        self.PolyOk.setObjectName(_fromUtf8("PolyOk"))
        self.gridLayout_10.addWidget(self.PolyOk, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.stackedWidget.addWidget(self.page_PolyCut)
        self.page_B_spline = QtGui.QWidget()
        self.page_B_spline.setObjectName(_fromUtf8("page_B_spline"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_B_spline)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_10 = QtGui.QGroupBox(self.page_B_spline)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_10)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.B_splineStep = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.B_splineStep.setDecimals(3)
        self.B_splineStep.setMinimum(0.001)
        self.B_splineStep.setMaximum(999999999.0)
        self.B_splineStep.setSingleStep(0.5)
        self.B_splineStep.setProperty("value", 1.0)
        self.B_splineStep.setObjectName(_fromUtf8("B_splineStep"))
        self.gridLayout_3.addWidget(self.B_splineStep, 1, 0, 1, 1)
        self.B_splineS = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.B_splineS.setDecimals(4)
        self.B_splineS.setMinimum(0.0)
        self.B_splineS.setMaximum(999999999.0)
        self.B_splineS.setSingleStep(0.05)
        self.B_splineS.setProperty("value", 1500000.0)
        self.B_splineS.setObjectName(_fromUtf8("B_splineS"))
        self.gridLayout_3.addWidget(self.B_splineS, 1, 1, 1, 1)
        self.B_splineK = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.B_splineK.setDecimals(0)
        self.B_splineK.setMinimum(1.0)
        self.B_splineK.setMaximum(5.0)
        self.B_splineK.setProperty("value", 4.0)
        self.B_splineK.setObjectName(_fromUtf8("B_splineK"))
        self.gridLayout_3.addWidget(self.B_splineK, 1, 2, 1, 1)
        self.AutoB_splineS = QtGui.QCheckBox(self.groupBox_10)
        self.AutoB_splineS.setObjectName(_fromUtf8("AutoB_splineS"))
        self.gridLayout_3.addWidget(self.AutoB_splineS, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_10)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_10)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)
        self.B_splineSmooth = QtGui.QCheckBox(self.groupBox_10)
        self.B_splineSmooth.setChecked(True)
        self.B_splineSmooth.setObjectName(_fromUtf8("B_splineSmooth"))
        self.gridLayout_3.addWidget(self.B_splineSmooth, 1, 3, 1, 1)
        self.B_splineOk = QtGui.QPushButton(self.groupBox_10)
        self.B_splineOk.setObjectName(_fromUtf8("B_splineOk"))
        self.gridLayout_3.addWidget(self.B_splineOk, 0, 4, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_10)
        self.stackedWidget.addWidget(self.page_B_spline)
        self.page_PolyFit = QtGui.QWidget()
        self.page_PolyFit.setObjectName(_fromUtf8("page_PolyFit"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_PolyFit)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_12 = QtGui.QGroupBox(self.page_PolyFit)
        self.groupBox_12.setEnabled(True)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 0, 0, 1, 1)
        self.ApproxM = QtGui.QSpinBox(self.groupBox_12)
        self.ApproxM.setMinimum(1)
        self.ApproxM.setSingleStep(1)
        self.ApproxM.setProperty("value", 4)
        self.ApproxM.setObjectName(_fromUtf8("ApproxM"))
        self.gridLayout_13.addWidget(self.ApproxM, 1, 1, 1, 1)
        self.PolyApprox = QtGui.QPushButton(self.groupBox_12)
        self.PolyApprox.setObjectName(_fromUtf8("PolyApprox"))
        self.gridLayout_13.addWidget(self.PolyApprox, 1, 3, 1, 1)
        self.ApproxStep = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.ApproxStep.setDecimals(4)
        self.ApproxStep.setMinimum(0.001)
        self.ApproxStep.setMaximum(10000.0)
        self.ApproxStep.setSingleStep(10000.0)
        self.ApproxStep.setObjectName(_fromUtf8("ApproxStep"))
        self.gridLayout_13.addWidget(self.ApproxStep, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_12)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_13.addWidget(self.label_9, 0, 1, 1, 1)
        self.ApproxPiece_wise = QtGui.QCheckBox(self.groupBox_12)
        self.ApproxPiece_wise.setObjectName(_fromUtf8("ApproxPiece_wise"))
        self.gridLayout_13.addWidget(self.ApproxPiece_wise, 1, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_12)
        self.stackedWidget.addWidget(self.page_PolyFit)
        self.page_Filters = QtGui.QWidget()
        self.page_Filters.setObjectName(_fromUtf8("page_Filters"))
        self.gridLayout = QtGui.QGridLayout(self.page_Filters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_22 = QtGui.QGroupBox(self.page_Filters)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.filtersList = QtGui.QListWidget(self.groupBox_22)
        self.filtersList.setObjectName(_fromUtf8("filtersList"))
        self.horizontalLayout_23.addWidget(self.filtersList)
        self.label_28 = QtGui.QLabel(self.groupBox_22)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.XFilt = QtGui.QLineEdit(self.groupBox_22)
        self.XFilt.setEnabled(True)
        self.XFilt.setObjectName(_fromUtf8("XFilt"))
        self.horizontalLayout_23.addWidget(self.XFilt)
        self.label_29 = QtGui.QLabel(self.groupBox_22)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_23.addWidget(self.label_29)
        self.YFilt = QtGui.QLineEdit(self.groupBox_22)
        self.YFilt.setEnabled(True)
        self.YFilt.setObjectName(_fromUtf8("YFilt"))
        self.horizontalLayout_23.addWidget(self.YFilt)
        self.FiltOk = QtGui.QPushButton(self.groupBox_22)
        self.FiltOk.setObjectName(_fromUtf8("FiltOk"))
        self.horizontalLayout_23.addWidget(self.FiltOk)
        self.gridLayout.addWidget(self.groupBox_22, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_Filters)
        self.page_Projects = QtGui.QWidget()
        self.page_Projects.setObjectName(_fromUtf8("page_Projects"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.page_Projects)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.projList = QtGui.QListWidget(self.page_Projects)
        self.projList.setObjectName(_fromUtf8("projList"))
        self.horizontalLayout_7.addWidget(self.projList)
        self.stackedWidget.addWidget(self.page_Projects)
        self.page_Plot = QtGui.QWidget()
        self.page_Plot.setObjectName(_fromUtf8("page_Plot"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.page_Plot)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(109, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_13 = QtGui.QLabel(self.page_Plot)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.mplhorizontalSlider = QtGui.QSlider(self.page_Plot)
        self.mplhorizontalSlider.setProperty("value", 3)
        self.mplhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mplhorizontalSlider.setObjectName(_fromUtf8("mplhorizontalSlider"))
        self.horizontalLayout_8.addWidget(self.mplhorizontalSlider)
        spacerItem1 = QtGui.QSpacerItem(109, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_15 = QtGui.QLabel(self.page_Plot)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.xLogScale = QtGui.QCheckBox(self.page_Plot)
        self.xLogScale.setObjectName(_fromUtf8("xLogScale"))
        self.horizontalLayout_8.addWidget(self.xLogScale)
        self.yLogScale = QtGui.QCheckBox(self.page_Plot)
        self.yLogScale.setObjectName(_fromUtf8("yLogScale"))
        self.horizontalLayout_8.addWidget(self.yLogScale)
        self.stackedWidget.addWidget(self.page_Plot)
        self.page_FiltFilt = QtGui.QWidget()
        self.page_FiltFilt.setObjectName(_fromUtf8("page_FiltFilt"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page_FiltFilt)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.FiltFiltK = QtGui.QSpinBox(self.page_FiltFilt)
        self.FiltFiltK.setProperty("value", 3)
        self.FiltFiltK.setObjectName(_fromUtf8("FiltFiltK"))
        self.horizontalLayout_9.addWidget(self.FiltFiltK)
        self.FiltFiltP = QtGui.QDoubleSpinBox(self.page_FiltFilt)
        self.FiltFiltP.setSingleStep(0.01)
        self.FiltFiltP.setProperty("value", 0.1)
        self.FiltFiltP.setObjectName(_fromUtf8("FiltFiltP"))
        self.horizontalLayout_9.addWidget(self.FiltFiltP)
        self.FiltFiltOk = QtGui.QPushButton(self.page_FiltFilt)
        self.FiltFiltOk.setObjectName(_fromUtf8("FiltFiltOk"))
        self.horizontalLayout_9.addWidget(self.FiltFiltOk)
        self.stackedWidget.addWidget(self.page_FiltFilt)
        self.page_Data = QtGui.QWidget()
        self.page_Data.setObjectName(_fromUtf8("page_Data"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_Data)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.isNormColumn = QtGui.QCheckBox(self.page_Data)
        self.isNormColumn.setObjectName(_fromUtf8("isNormColumn"))
        self.gridLayout_4.addWidget(self.isNormColumn, 2, 8, 1, 1)
        self.deleteData = QtGui.QToolButton(self.page_Data)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/Reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteData.setIcon(icon)
        self.deleteData.setObjectName(_fromUtf8("deleteData"))
        self.gridLayout_4.addWidget(self.deleteData, 0, 3, 1, 1)
        self.xColumn = QtGui.QSpinBox(self.page_Data)
        self.xColumn.setProperty("value", 1)
        self.xColumn.setObjectName(_fromUtf8("xColumn"))
        self.gridLayout_4.addWidget(self.xColumn, 2, 6, 1, 1)
        self.mColumn = QtGui.QSpinBox(self.page_Data)
        self.mColumn.setEnabled(False)
        self.mColumn.setProperty("value", 2)
        self.mColumn.setObjectName(_fromUtf8("mColumn"))
        self.gridLayout_4.addWidget(self.mColumn, 3, 8, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_Data)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 3, 5, 1, 1)
        self.yColumn = QtGui.QSpinBox(self.page_Data)
        self.yColumn.setProperty("value", 3)
        self.yColumn.setObjectName(_fromUtf8("yColumn"))
        self.gridLayout_4.addWidget(self.yColumn, 3, 6, 1, 1)
        self.namesTable = QtGui.QTableWidget(self.page_Data)
        self.namesTable.setMaximumSize(QtCore.QSize(400, 100))
        self.namesTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.namesTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.namesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.namesTable.setColumnCount(1)
        self.namesTable.setObjectName(_fromUtf8("namesTable"))
        self.namesTable.setRowCount(0)
        self.namesTable.horizontalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.namesTable, 0, 0, 4, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 4, 4, 1)
        self.label = QtGui.QLabel(self.page_Data)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 2, 5, 1, 1)
        self.saveData = QtGui.QToolButton(self.page_Data)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.saveData.setIcon(icon)
        self.saveData.setObjectName(_fromUtf8("saveData"))
        self.gridLayout_4.addWidget(self.saveData, 3, 3, 1, 1)
        self.rowMoveDown = QtGui.QToolButton(self.page_Data)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("down"))
        self.rowMoveDown.setIcon(icon)
        self.rowMoveDown.setObjectName(_fromUtf8("rowMoveDown"))
        self.gridLayout_4.addWidget(self.rowMoveDown, 2, 3, 1, 1)
        self.rowMoveUp = QtGui.QToolButton(self.page_Data)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("up"))
        self.rowMoveUp.setIcon(icon)
        self.rowMoveUp.setObjectName(_fromUtf8("rowMoveUp"))
        self.gridLayout_4.addWidget(self.rowMoveUp, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_Data)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 5, 1, 1)
        self.delimiter = QtGui.QComboBox(self.page_Data)
        self.delimiter.setObjectName(_fromUtf8("delimiter"))
        self.delimiter.addItem(_fromUtf8(""))
        self.delimiter.addItem(_fromUtf8(""))
        self.delimiter.addItem(_fromUtf8(""))
        self.delimiter.addItem(_fromUtf8(""))
        self.delimiter.addItem(_fromUtf8(""))
        self.delimiter.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.delimiter, 1, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_Data)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 8, 1, 1)
        self.filePath = QtGui.QLineEdit(self.page_Data)
        self.filePath.setEchoMode(QtGui.QLineEdit.Normal)
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.gridLayout_4.addWidget(self.filePath, 0, 5, 1, 5)
        self.selectFile = QtGui.QToolButton(self.page_Data)
        self.selectFile.setObjectName(_fromUtf8("selectFile"))
        self.gridLayout_4.addWidget(self.selectFile, 0, 10, 1, 1)
        self.selectPartOfData = QtGui.QComboBox(self.page_Data)
        self.selectPartOfData.setObjectName(_fromUtf8("selectPartOfData"))
        self.selectPartOfData.addItem(_fromUtf8(""))
        self.selectPartOfData.addItem(_fromUtf8(""))
        self.selectPartOfData.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.selectPartOfData, 1, 9, 1, 1)
        self.addToTable = QtGui.QPushButton(self.page_Data)
        self.addToTable.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("add"))
        self.addToTable.setIcon(icon)
        self.addToTable.setObjectName(_fromUtf8("addToTable"))
        self.gridLayout_4.addWidget(self.addToTable, 3, 10, 1, 1)
        self.line = QtGui.QFrame(self.page_Data)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 7, 3, 1)
        self.stackedWidget.addWidget(self.page_Data)
        self.page_NormData = QtGui.QWidget()
        self.page_NormData.setObjectName(_fromUtf8("page_NormData"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_NormData)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.yInPercents = QtGui.QCheckBox(self.page_NormData)
        self.yInPercents.setObjectName(_fromUtf8("yInPercents"))
        self.gridLayout_2.addWidget(self.yInPercents, 2, 2, 1, 1)
        self.normDataRemove = QtGui.QToolButton(self.page_NormData)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("remove"))
        self.normDataRemove.setIcon(icon)
        self.normDataRemove.setObjectName(_fromUtf8("normDataRemove"))
        self.gridLayout_2.addWidget(self.normDataRemove, 0, 2, 1, 1)
        self.normDataAdd = QtGui.QToolButton(self.page_NormData)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("add"))
        self.normDataAdd.setIcon(icon)
        self.normDataAdd.setObjectName(_fromUtf8("normDataAdd"))
        self.gridLayout_2.addWidget(self.normDataAdd, 0, 1, 1, 1)
        self.normEvalType = QtGui.QComboBox(self.page_NormData)
        self.normEvalType.setObjectName(_fromUtf8("normEvalType"))
        self.normEvalType.addItem(_fromUtf8(""))
        self.normEvalType.addItem(_fromUtf8(""))
        self.normEvalType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.normEvalType, 1, 2, 1, 2)
        self.normTable = QtGui.QTableWidget(self.page_NormData)
        self.normTable.setObjectName(_fromUtf8("normTable"))
        self.normTable.setColumnCount(5)
        self.normTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.normTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.normTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.normTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.normTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.normTable.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.normTable, 0, 0, 3, 1)
        self.stackedWidget.addWidget(self.page_NormData)
        self.page_ReHi3 = QtGui.QWidget()
        self.page_ReHi3.setObjectName(_fromUtf8("page_ReHi3"))
        self.formLayout = QtGui.QFormLayout(self.page_ReHi3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.line_2 = QtGui.QFrame(self.page_ReHi3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.line_2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.page_ReHi3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.reHi3_n0 = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_n0.setSingleStep(0.1)
        self.reHi3_n0.setProperty("value", 1.0)
        self.reHi3_n0.setObjectName(_fromUtf8("reHi3_n0"))
        self.gridLayout_5.addWidget(self.reHi3_n0, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_ReHi3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.reHi3_r0 = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_r0.setMaximum(999.99)
        self.reHi3_r0.setProperty("value", 0.1)
        self.reHi3_r0.setObjectName(_fromUtf8("reHi3_r0"))
        self.gridLayout_5.addWidget(self.reHi3_r0, 1, 8, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_ReHi3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 9, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_ReHi3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 7, 1, 1)
        self.reHi3_d = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_d.setMaximum(999.99)
        self.reHi3_d.setProperty("value", 1.0)
        self.reHi3_d.setObjectName(_fromUtf8("reHi3_d"))
        self.gridLayout_5.addWidget(self.reHi3_d, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.page_ReHi3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 6, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_ReHi3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 8, 1, 1)
        self.reHi3_a0 = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_a0.setMaximum(1000.0)
        self.reHi3_a0.setProperty("value", 25.0)
        self.reHi3_a0.setObjectName(_fromUtf8("reHi3_a0"))
        self.gridLayout_5.addWidget(self.reHi3_a0, 1, 1, 1, 1)
        self.reHi3_dM = QtGui.QComboBox(self.page_ReHi3)
        self.reHi3_dM.setMaximumSize(QtCore.QSize(70, 16777215))
        self.reHi3_dM.setObjectName(_fromUtf8("reHi3_dM"))
        self.reHi3_dM.addItem(_fromUtf8(""))
        self.reHi3_dM.addItem(_fromUtf8(""))
        self.reHi3_dM.addItem(_fromUtf8(""))
        self.reHi3_dM.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.reHi3_dM, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_ReHi3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.reHi3_lambda = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_lambda.setMaximum(10000.0)
        self.reHi3_lambda.setProperty("value", 532.0)
        self.reHi3_lambda.setObjectName(_fromUtf8("reHi3_lambda"))
        self.gridLayout_5.addWidget(self.reHi3_lambda, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_ReHi3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 5, 1, 1)
        self.reHi3_f = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_f.setMaximum(999.99)
        self.reHi3_f.setProperty("value", 8.0)
        self.reHi3_f.setObjectName(_fromUtf8("reHi3_f"))
        self.gridLayout_5.addWidget(self.reHi3_f, 1, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_ReHi3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 3, 1, 2)
        self.reHi3_l = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_l.setMaximum(999.99)
        self.reHi3_l.setProperty("value", 11.0)
        self.reHi3_l.setObjectName(_fromUtf8("reHi3_l"))
        self.gridLayout_5.addWidget(self.reHi3_l, 1, 6, 1, 1)
        self.reHi3_z = QtGui.QDoubleSpinBox(self.page_ReHi3)
        self.reHi3_z.setMaximum(999.99)
        self.reHi3_z.setProperty("value", 80.0)
        self.reHi3_z.setObjectName(_fromUtf8("reHi3_z"))
        self.gridLayout_5.addWidget(self.reHi3_z, 1, 5, 1, 1)
        self.reHi3_polyM = QtGui.QSpinBox(self.page_ReHi3)
        self.reHi3_polyM.setMinimum(1)
        self.reHi3_polyM.setMaximum(3)
        self.reHi3_polyM.setObjectName(_fromUtf8("reHi3_polyM"))
        self.gridLayout_5.addWidget(self.reHi3_polyM, 1, 9, 1, 1)
        self.reHi3_ok = QtGui.QPushButton(self.page_ReHi3)
        self.reHi3_ok.setObjectName(_fromUtf8("reHi3_ok"))
        self.gridLayout_5.addWidget(self.reHi3_ok, 0, 10, 2, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_5)
        self.reHi3_console = QtGui.QScrollArea(self.page_ReHi3)
        self.reHi3_console.setWidgetResizable(True)
        self.reHi3_console.setObjectName(_fromUtf8("reHi3_console"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 44))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.reHi3_console.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.reHi3_console)
        self.stackedWidget.addWidget(self.page_ReHi3)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1005, 28))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_norm = QtGui.QMenu(self.menu_2)
        self.menu_norm.setTearOffEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/norm_On.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_norm.setIcon(icon1)
        self.menu_norm.setObjectName(_fromUtf8("menu_norm"))
        self.menu_Scale = QtGui.QMenu(self.menu_2)
        self.menu_Scale.setObjectName(_fromUtf8("menu_Scale"))
        self.menu_5 = QtGui.QMenu(self.menu_2)
        self.menu_5.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-cut"))
        self.menu_5.setIcon(icon)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_8 = QtGui.QMenu(self.menu_2)
        self.menu_8.setObjectName(_fromUtf8("menu_8"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menuBar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_Hist = QtGui.QMenu(self.menuBar)
        self.menu_Hist.setObjectName(_fromUtf8("menu_Hist"))
        self.projects = QtGui.QMenu(self.menuBar)
        self.projects.setObjectName(_fromUtf8("projects"))
        self.addToProjMenu = QtGui.QMenu(self.projects)
        self.addToProjMenu.setObjectName(_fromUtf8("addToProjMenu"))
        self.menu_7 = QtGui.QMenu(self.menuBar)
        self.menu_7.setObjectName(_fromUtf8("menu_7"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBarGraph = QtGui.QToolBar(MainWindow)
        self.toolBarGraph.setAcceptDrops(False)
        self.toolBarGraph.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBarGraph.setFloatable(True)
        self.toolBarGraph.setObjectName(_fromUtf8("toolBarGraph"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBarGraph)
        self.ToolBarMpl_cut = QtGui.QToolBar(MainWindow)
        self.ToolBarMpl_cut.setObjectName(_fromUtf8("ToolBarMpl_cut"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.ToolBarMpl_cut)
        self.toolBarScale = QtGui.QToolBar(MainWindow)
        self.toolBarScale.setObjectName(_fromUtf8("toolBarScale"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBarScale)
        self.toolBarHistory = QtGui.QToolBar(MainWindow)
        self.toolBarHistory.setObjectName(_fromUtf8("toolBarHistory"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBarHistory)
        self.instruments = QtGui.QToolBar(MainWindow)
        self.instruments.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.instruments.setObjectName(_fromUtf8("instruments"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.instruments)
        self.saveSettings = QtGui.QAction(MainWindow)
        self.saveSettings.setObjectName(_fromUtf8("saveSettings"))
        self.loadSettings = QtGui.QAction(MainWindow)
        self.loadSettings.setObjectName(_fromUtf8("loadSettings"))
        self.recalcIntens = QtGui.QAction(MainWindow)
        self.recalcIntens.setObjectName(_fromUtf8("recalcIntens"))
        self.Discrete = QtGui.QAction(MainWindow)
        self.Discrete.setCheckable(True)
        self.Discrete.setObjectName(_fromUtf8("Discrete"))
        self.Close = QtGui.QAction(MainWindow)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.actionY_X = QtGui.QAction(MainWindow)
        self.actionY_X.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/Y_X.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionY_X.setIcon(icon2)
        self.actionY_X.setObjectName(_fromUtf8("actionY_X"))
        self.actionX_Log10 = QtGui.QAction(MainWindow)
        self.actionX_Log10.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/LgX.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionX_Log10.setIcon(icon3)
        self.actionX_Log10.setObjectName(_fromUtf8("actionX_Log10"))
        self.actionY_Log10 = QtGui.QAction(MainWindow)
        self.actionY_Log10.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/LgY.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionY_Log10.setIcon(icon4)
        self.actionY_Log10.setObjectName(_fromUtf8("actionY_Log10"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setEnabled(False)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.processAll = QtGui.QAction(MainWindow)
        self.processAll.setCheckable(True)
        self.processAll.setChecked(True)
        self.processAll.setObjectName(_fromUtf8("processAll"))
        self.processView = QtGui.QAction(MainWindow)
        self.processView.setCheckable(True)
        self.processView.setObjectName(_fromUtf8("processView"))
        self.Undo = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/Undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Undo.setIcon(icon5)
        self.Undo.setMenuRole(QtGui.QAction.ApplicationSpecificRole)
        self.Undo.setObjectName(_fromUtf8("Undo"))
        self.Reset = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("remove"))
        self.Reset.setIcon(icon)
        self.Reset.setObjectName(_fromUtf8("Reset"))
        self.norm_Max = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/norm_Max.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_Max.setIcon(icon6)
        self.norm_Max.setObjectName(_fromUtf8("norm_Max"))
        self.norm_Point = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/norm_Point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_Point.setIcon(icon7)
        self.norm_Point.setObjectName(_fromUtf8("norm_Point"))
        self.settings = QtGui.QAction(MainWindow)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.createProj = QtGui.QAction(MainWindow)
        self.createProj.setObjectName(_fromUtf8("createProj"))
        self.norm_FirstPoint = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/norm_FirstPoint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.norm_FirstPoint.setIcon(icon8)
        self.norm_FirstPoint.setObjectName(_fromUtf8("norm_FirstPoint"))
        self.autoScale = QtGui.QAction(MainWindow)
        self.autoScale.setCheckable(True)
        self.autoScale.setChecked(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/Rescale.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoScale.setIcon(icon9)
        self.autoScale.setObjectName(_fromUtf8("autoScale"))
        self.tmpShow = QtGui.QAction(MainWindow)
        self.tmpShow.setCheckable(True)
        self.tmpShow.setChecked(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/ShowTmp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tmpShow.setIcon(icon10)
        self.tmpShow.setObjectName(_fromUtf8("tmpShow"))
        self.mplactionCut_by_line = QtGui.QAction(MainWindow)
        self.mplactionCut_by_line.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mplactionCut_by_line.setIcon(icon11)
        self.mplactionCut_by_line.setObjectName(_fromUtf8("mplactionCut_by_line"))
        self.mplactionCut_by_rect = QtGui.QAction(MainWindow)
        self.mplactionCut_by_rect.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/rect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mplactionCut_by_rect.setIcon(icon12)
        self.mplactionCut_by_rect.setObjectName(_fromUtf8("mplactionCut_by_rect"))
        self.movePoint = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/movePoint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movePoint.setIcon(icon13)
        self.movePoint.setObjectName(_fromUtf8("movePoint"))
        self.console = QtGui.QAction(MainWindow)
        self.console.setObjectName(_fromUtf8("console"))
        self.actionAverage = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/average.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAverage.setIcon(icon14)
        self.actionAverage.setObjectName(_fromUtf8("actionAverage"))
        self.actionFiltFilt = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/filtfilt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFiltFilt.setIcon(icon15)
        self.actionFiltFilt.setObjectName(_fromUtf8("actionFiltFilt"))
        self.actionB_spline = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/b_spline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionB_spline.setIcon(icon16)
        self.actionB_spline.setObjectName(_fromUtf8("actionB_spline"))
        self.actionPolyFit = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/polyFit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyFit.setIcon(icon17)
        self.actionPolyFit.setObjectName(_fromUtf8("actionPolyFit"))
        self.actionPolyCut = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/polyCut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyCut.setIcon(icon18)
        self.actionPolyCut.setObjectName(_fromUtf8("actionPolyCut"))
        self.actionOpenFiles = QtGui.QAction(MainWindow)
        self.actionOpenFiles.setObjectName(_fromUtf8("actionOpenFiles"))
        self.actionData = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/selectData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData.setIcon(icon19)
        self.actionData.setObjectName(_fromUtf8("actionData"))
        self.actionNormData = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/normData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormData.setIcon(icon20)
        self.actionNormData.setObjectName(_fromUtf8("actionNormData"))
        self.actionReHi3 = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/reHi3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReHi3.setIcon(icon21)
        self.actionReHi3.setObjectName(_fromUtf8("actionReHi3"))
        self.actionFilters = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/ui/buttons/filters.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilters.setIcon(icon22)
        self.actionFilters.setObjectName(_fromUtf8("actionFilters"))
        self.actionSaveData = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("filesave"))
        self.actionSaveData.setIcon(icon)
        self.actionSaveData.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSaveData.setObjectName(_fromUtf8("actionSaveData"))
        self.menu.addAction(self.settings)
        self.menu_norm.addAction(self.norm_Max)
        self.menu_norm.addAction(self.norm_Point)
        self.menu_norm.addAction(self.norm_FirstPoint)
        self.menu_Scale.addAction(self.actionY_Log10)
        self.menu_Scale.addAction(self.actionX_Log10)
        self.menu_Scale.addAction(self.actionY_X)
        self.menu_5.addAction(self.mplactionCut_by_line)
        self.menu_5.addAction(self.mplactionCut_by_rect)
        self.menu_8.addAction(self.actionFiltFilt)
        self.menu_2.addAction(self.recalcIntens)
        self.menu_2.addAction(self.actionFilters)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_Scale.menuAction())
        self.menu_2.addAction(self.autoScale)
        self.menu_2.addAction(self.tmpShow)
        self.menu_2.addAction(self.menu_norm.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_5.menuAction())
        self.menu_2.addAction(self.movePoint)
        self.menu_2.addAction(self.menu_8.menuAction())
        self.menu_2.addAction(self.actionAverage)
        self.menu_2.addAction(self.actionB_spline)
        self.menu_2.addAction(self.actionPolyFit)
        self.menu_2.addAction(self.actionPolyCut)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionNormData)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionReHi3)
        self.menu_3.addAction(self.Discrete)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.processView)
        self.menu_4.addAction(self.actionOpenFiles)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actionData)
        self.menu_4.addAction(self.actionSaveData)
        self.menu_4.addAction(self.Close)
        self.menu_Hist.addAction(self.Undo)
        self.menu_Hist.addAction(self.Reset)
        self.addToProjMenu.addSeparator()
        self.projects.addAction(self.createProj)
        self.projects.addSeparator()
        self.projects.addAction(self.addToProjMenu.menuAction())
        self.menu_7.addAction(self.console)
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_Hist.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.projects.menuAction())
        self.menuBar.addAction(self.menu_7.menuAction())
        self.toolBarGraph.addAction(self.autoScale)
        self.toolBarGraph.addAction(self.tmpShow)
        self.ToolBarMpl_cut.addAction(self.mplactionCut_by_line)
        self.ToolBarMpl_cut.addAction(self.mplactionCut_by_rect)
        self.ToolBarMpl_cut.addAction(self.movePoint)
        self.toolBarScale.addAction(self.actionY_X)
        self.toolBarScale.addAction(self.actionX_Log10)
        self.toolBarScale.addAction(self.actionY_Log10)
        self.toolBarHistory.addAction(self.Undo)
        self.toolBarHistory.addAction(self.Reset)
        self.instruments.addAction(self.actionData)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionPolyCut)
        self.instruments.addAction(self.actionPolyFit)
        self.instruments.addAction(self.actionB_spline)
        self.instruments.addAction(self.actionFiltFilt)
        self.instruments.addAction(self.actionAverage)
        self.instruments.addAction(self.actionFilters)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionNormData)
        self.instruments.addSeparator()
        self.instruments.addAction(self.actionReHi3)
        self.instruments.addSeparator()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mplhorizontalSlider, self.xLogScale)
        MainWindow.setTabOrder(self.xLogScale, self.yLogScale)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QTR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", " Усереднення", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.AverageOk.setText(QtGui.QApplication.translate("MainWindow", "Усереднити", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізання вздовж поліном. апроксимації", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.PolyOk.setText(QtGui.QApplication.translate("MainWindow", "Обрізати", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "В-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін.", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoB_splineS.setText(QtGui.QApplication.translate("MainWindow", "авто", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "крок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Згладжув.", None, QtGui.QApplication.UnicodeUTF8))
        self.B_splineSmooth.setText(QtGui.QApplication.translate("MainWindow", "Згладж.", None, QtGui.QApplication.UnicodeUTF8))
        self.B_splineOk.setText(QtGui.QApplication.translate("MainWindow", "Інтерпол.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Апроксимувати поліномом", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Крок", None, QtGui.QApplication.UnicodeUTF8))
        self.PolyApprox.setText(QtGui.QApplication.translate("MainWindow", "Апрокс.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Степ. полін", None, QtGui.QApplication.UnicodeUTF8))
        self.ApproxPiece_wise.setText(QtGui.QApplication.translate("MainWindow", "Шматкова апрокс.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_22.setTitle(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.FiltOk.setText(QtGui.QApplication.translate("MainWindow", "Застосувати", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Розмір точок: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Log10:", None, QtGui.QApplication.UnicodeUTF8))
        self.xLogScale.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.yLogScale.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.FiltFiltOk.setText(QtGui.QApplication.translate("MainWindow", "ok", None, QtGui.QApplication.UnicodeUTF8))
        self.isNormColumn.setText(QtGui.QApplication.translate("MainWindow", "Норм.", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteData.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.saveData.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rowMoveDown.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rowMoveUp.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Розділювач", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(0, QtGui.QApplication.translate("MainWindow", "space space", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(1, QtGui.QApplication.translate("MainWindow", "space", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(2, QtGui.QApplication.translate("MainWindow", "tab", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(3, QtGui.QApplication.translate("MainWindow", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(4, QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.delimiter.setItemText(5, QtGui.QApplication.translate("MainWindow", ";", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.selectFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPartOfData.setItemText(0, QtGui.QApplication.translate("MainWindow", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPartOfData.setItemText(1, QtGui.QApplication.translate("MainWindow", "Вперед", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPartOfData.setItemText(2, QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.addToTable.setText(QtGui.QApplication.translate("MainWindow", "Додати", None, QtGui.QApplication.UnicodeUTF8))
        self.yInPercents.setText(QtGui.QApplication.translate("MainWindow", "Y, %", None, QtGui.QApplication.UnicodeUTF8))
        self.normDataRemove.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.normDataAdd.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.normEvalType.setItemText(0, QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.normEvalType.setItemText(1, QtGui.QApplication.translate("MainWindow", "nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.normEvalType.setItemText(2, QtGui.QApplication.translate("MainWindow", "zero", None, QtGui.QApplication.UnicodeUTF8))
        item = self.normTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Чисельник", None, QtGui.QApplication.UnicodeUTF8))
        item = self.normTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Знаменник", None, QtGui.QApplication.UnicodeUTF8))
        item = self.normTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Назва", None, QtGui.QApplication.UnicodeUTF8))
        item = self.normTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Стан", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>A<span style=\" vertical-align:sub;\">0</span>, px</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>n<span style=\" vertical-align:sub;\">0</span><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">0</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "f, см", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "l, см", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>r<span style=\" vertical-align:sub;\">0</span>, см</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reHi3_dM.setItemText(0, QtGui.QApplication.translate("MainWindow", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.reHi3_dM.setItemText(1, QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.reHi3_dM.setItemText(2, QtGui.QApplication.translate("MainWindow", "mkm", None, QtGui.QApplication.UnicodeUTF8))
        self.reHi3_dM.setItemText(3, QtGui.QApplication.translate("MainWindow", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>λ, нм</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "z, см", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.reHi3_ok.setText(QtGui.QApplication.translate("MainWindow", "Ок", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Налаштування", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Обробка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_norm.setTitle(QtGui.QApplication.translate("MainWindow", "Нормувати", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Scale.setTitle(QtGui.QApplication.translate("MainWindow", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_5.setTitle(QtGui.QApplication.translate("MainWindow", "Обрізка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_8.setTitle(QtGui.QApplication.translate("MainWindow", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Режим", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Hist.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.projects.setTitle(QtGui.QApplication.translate("MainWindow", "Проект", None, QtGui.QApplication.UnicodeUTF8))
        self.addToProjMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Додати до існуючого", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_7.setTitle(QtGui.QApplication.translate("MainWindow", "Інструменти", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarGraph.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBarMpl_cut.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarScale.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarHistory.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettings.setText(QtGui.QApplication.translate("MainWindow", "зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettings.setText(QtGui.QApplication.translate("MainWindow", "завантажити", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcIntens.setText(QtGui.QApplication.translate("MainWindow", "Посадити на інтенсивність", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcIntens.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.Discrete.setText(QtGui.QApplication.translate("MainWindow", "Дискретний", None, QtGui.QApplication.UnicodeUTF8))
        self.Discrete.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("MainWindow", "Вийти", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q, Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_X.setText(QtGui.QApplication.translate("MainWindow", "y -> Y/X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_Log10.setText(QtGui.QApplication.translate("MainWindow", "x -> Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_Log10.setText(QtGui.QApplication.translate("MainWindow", "y -> Log10", None, QtGui.QApplication.UnicodeUTF8))
        self.action_5.setText(QtGui.QApplication.translate("MainWindow", "Межі обробки:", None, QtGui.QApplication.UnicodeUTF8))
        self.processAll.setText(QtGui.QApplication.translate("MainWindow", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.processView.setText(QtGui.QApplication.translate("MainWindow", "Видимий діапазон", None, QtGui.QApplication.UnicodeUTF8))
        self.Undo.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.Undo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setText(QtGui.QApplication.translate("MainWindow", "Скинути", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_Max.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на максимум", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_Point.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на вказану точку", None, QtGui.QApplication.UnicodeUTF8))
        self.settings.setText(QtGui.QApplication.translate("MainWindow", "Параметри", None, QtGui.QApplication.UnicodeUTF8))
        self.createProj.setText(QtGui.QApplication.translate("MainWindow", "Створити", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_FirstPoint.setText(QtGui.QApplication.translate("MainWindow", "Нормувати на першу точку", None, QtGui.QApplication.UnicodeUTF8))
        self.autoScale.setText(QtGui.QApplication.translate("MainWindow", "Автомасштабування", None, QtGui.QApplication.UnicodeUTF8))
        self.tmpShow.setText(QtGui.QApplication.translate("MainWindow", "Проміжні побудови", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionCut_by_line.setText(QtGui.QApplication.translate("MainWindow", "Лінією", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionCut_by_rect.setText(QtGui.QApplication.translate("MainWindow", "Прямокутником", None, QtGui.QApplication.UnicodeUTF8))
        self.movePoint.setText(QtGui.QApplication.translate("MainWindow", "Перемістити точки", None, QtGui.QApplication.UnicodeUTF8))
        self.console.setText(QtGui.QApplication.translate("MainWindow", "Консоль", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAverage.setText(QtGui.QApplication.translate("MainWindow", "average", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFiltFilt.setText(QtGui.QApplication.translate("MainWindow", "filtfilt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionB_spline.setText(QtGui.QApplication.translate("MainWindow", "b-spline", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPolyFit.setText(QtGui.QApplication.translate("MainWindow", "polyFit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPolyCut.setText(QtGui.QApplication.translate("MainWindow", "polyCut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFiles.setText(QtGui.QApplication.translate("MainWindow", "Відкрити файли", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData.setText(QtGui.QApplication.translate("MainWindow", "вибрати дані", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormData.setText(QtGui.QApplication.translate("MainWindow", "Нормувати", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReHi3.setText(QtGui.QApplication.translate("MainWindow", "Обчислити Re(hi3)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilters.setText(QtGui.QApplication.translate("MainWindow", "Посадити на фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveData.setText(QtGui.QApplication.translate("MainWindow", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveData.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

from ui.mplwidget import MplWidget
import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

