# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kronosua/work/QTR/ui/intens.ui'
#
# Created: Sat Feb  9 23:02:38 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(696, 680)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.length = QtGui.QDoubleSpinBox(Dialog)
        self.length.setMinimum(0.01)
        self.length.setMaximum(5000.0)
        self.length.setProperty("value", 1064.0)
        self.length.setObjectName(_fromUtf8("length"))
        self.gridLayout.addWidget(self.length, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.Z = QtGui.QDoubleSpinBox(Dialog)
        self.Z.setMinimum(0.01)
        self.Z.setMaximum(1000.0)
        self.Z.setProperty("value", 15.0)
        self.Z.setObjectName(_fromUtf8("Z"))
        self.gridLayout.addWidget(self.Z, 1, 2, 1, 1)
        self.F = QtGui.QDoubleSpinBox(Dialog)
        self.F.setMinimum(0.01)
        self.F.setMaximum(1000.0)
        self.F.setProperty("value", 8.0)
        self.F.setObjectName(_fromUtf8("F"))
        self.gridLayout.addWidget(self.F, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.R = QtGui.QDoubleSpinBox(Dialog)
        self.R.setMinimum(0.01)
        self.R.setMaximum(1000.0)
        self.R.setProperty("value", 25.0)
        self.R.setObjectName(_fromUtf8("R"))
        self.gridLayout.addWidget(self.R, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.recalcAi2 = QtGui.QPushButton(Dialog)
        self.recalcAi2.setObjectName(_fromUtf8("recalcAi2"))
        self.horizontalLayout.addWidget(self.recalcAi2)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.Ai2 = QtGui.QLineEdit(Dialog)
        self.Ai2.setReadOnly(True)
        self.Ai2.setObjectName(_fromUtf8("Ai2"))
        self.horizontalLayout.addWidget(self.Ai2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.namesList = QtGui.QListWidget(Dialog)
        self.namesList.setObjectName(_fromUtf8("namesList"))
        self.verticalLayout.addWidget(self.namesList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.file = QtGui.QPushButton(Dialog)
        self.file.setObjectName(_fromUtf8("file"))
        self.horizontalLayout_2.addWidget(self.file)
        self.recalcCalibr = QtGui.QPushButton(Dialog)
        self.recalcCalibr.setObjectName(_fromUtf8("recalcCalibr"))
        self.horizontalLayout_2.addWidget(self.recalcCalibr)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_16 = QtGui.QGroupBox(Dialog)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.calibr = QtGui.QLineEdit(self.groupBox_16)
        self.calibr.setMaxLength(50)
        self.calibr.setObjectName(_fromUtf8("calibr"))
        self.gridLayout_5.addWidget(self.calibr, 0, 2, 1, 1)
        self.intensFilt = QtGui.QLineEdit(self.groupBox_16)
        self.intensFilt.setObjectName(_fromUtf8("intensFilt"))
        self.gridLayout_5.addWidget(self.intensFilt, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_16)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_16)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_16)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.recalcResult = QtGui.QPushButton(Dialog)
        self.recalcResult.setObjectName(_fromUtf8("recalcResult"))
        self.horizontalLayout_6.addWidget(self.recalcResult)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.result = QtGui.QLineEdit(Dialog)
        self.result.setObjectName(_fromUtf8("result"))
        self.horizontalLayout_6.addWidget(self.result)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.activeDataType = QtGui.QComboBox(self.groupBox)
        self.activeDataType.setObjectName(_fromUtf8("activeDataType"))
        self.activeDataType.addItem(_fromUtf8(""))
        self.activeDataType.addItem(_fromUtf8(""))
        self.activeDataType.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.activeDataType)
        self.applyForActiveData = QtGui.QPushButton(self.groupBox)
        self.applyForActiveData.setObjectName(_fromUtf8("applyForActiveData"))
        self.horizontalLayout_4.addWidget(self.applyForActiveData)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.applyFilesList = QtGui.QListWidget(self.groupBox)
        self.applyFilesList.setObjectName(_fromUtf8("applyFilesList"))
        self.verticalLayout_2.addWidget(self.applyFilesList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.getFilesForRecalc = QtGui.QPushButton(self.groupBox)
        self.getFilesForRecalc.setObjectName(_fromUtf8("getFilesForRecalc"))
        self.horizontalLayout_3.addWidget(self.getFilesForRecalc)
        self.xColumn = QtGui.QSpinBox(self.groupBox)
        self.xColumn.setObjectName(_fromUtf8("xColumn"))
        self.horizontalLayout_3.addWidget(self.xColumn)
        self.saveSuffix = QtGui.QLineEdit(self.groupBox)
        self.saveSuffix.setObjectName(_fromUtf8("saveSuffix"))
        self.horizontalLayout_3.addWidget(self.saveSuffix)
        self.applyForFiles = QtGui.QPushButton(self.groupBox)
        self.applyForFiles.setObjectName(_fromUtf8("applyForFiles"))
        self.horizontalLayout_3.addWidget(self.applyForFiles)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.hideWindow = QtGui.QPushButton(Dialog)
        self.hideWindow.setObjectName(_fromUtf8("hideWindow"))
        self.verticalLayout.addWidget(self.hideWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.xColumn, self.applyForFiles)
        Dialog.setTabOrder(self.applyForFiles, self.length)
        Dialog.setTabOrder(self.length, self.F)
        Dialog.setTabOrder(self.F, self.Z)
        Dialog.setTabOrder(self.Z, self.R)
        Dialog.setTabOrder(self.R, self.Ai2)
        Dialog.setTabOrder(self.Ai2, self.namesList)
        Dialog.setTabOrder(self.namesList, self.file)
        Dialog.setTabOrder(self.file, self.recalcCalibr)
        Dialog.setTabOrder(self.recalcCalibr, self.calibr)
        Dialog.setTabOrder(self.calibr, self.intensFilt)
        Dialog.setTabOrder(self.intensFilt, self.result)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "intensDialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Відстань від лінзи, см", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Фокусна відстань, см", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Довж. хвилі, нм", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Радіус, пучка, px (25 мкм)", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcAi2.setText(QtGui.QApplication.translate("Dialog", "Обчислити", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Ai2 =", None, QtGui.QApplication.UnicodeUTF8))
        self.file.setText(QtGui.QApplication.translate("Dialog", "Вибрати", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcCalibr.setText(QtGui.QApplication.translate("Dialog", "Обчислити коеф. калібр.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("Dialog", "Інтенсивність", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Коефіцієнт калібровки:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Dialog", "Фільтри", None, QtGui.QApplication.UnicodeUTF8))
        self.recalcResult.setText(QtGui.QApplication.translate("Dialog", "Обчислити", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Результуючий множник:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Застосувати до:", None, QtGui.QApplication.UnicodeUTF8))
        self.activeDataType.setItemText(0, QtGui.QApplication.translate("Dialog", "Результат", None, QtGui.QApplication.UnicodeUTF8))
        self.activeDataType.setItemText(1, QtGui.QApplication.translate("Dialog", "Зразок", None, QtGui.QApplication.UnicodeUTF8))
        self.activeDataType.setItemText(2, QtGui.QApplication.translate("Dialog", "Крос", None, QtGui.QApplication.UnicodeUTF8))
        self.applyForActiveData.setText(QtGui.QApplication.translate("Dialog", "Застосувати", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Або:", None, QtGui.QApplication.UnicodeUTF8))
        self.getFilesForRecalc.setText(QtGui.QApplication.translate("Dialog", "Файли", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSuffix.setPlaceholderText(QtGui.QApplication.translate("Dialog", "суфікс", None, QtGui.QApplication.UnicodeUTF8))
        self.applyForFiles.setText(QtGui.QApplication.translate("Dialog", "Зберегти", None, QtGui.QApplication.UnicodeUTF8))
        self.hideWindow.setText(QtGui.QApplication.translate("Dialog", "Закрити", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

